// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db_data_2025-01.proto
// Protobuf Java Version: 4.29.3

package io.pinecone.proto;

public final class DbData202501 {
  private DbData202501() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      DbData202501.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SparseValues_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SparseValues_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Vector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Vector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ScoredVector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ScoredVector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestUnion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RequestUnion_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpsertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UpsertRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpsertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UpsertResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DeleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FetchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FetchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FetchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FetchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FetchResponse_VectorsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FetchResponse_VectorsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pagination_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Pagination_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ListItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryVector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_QueryVector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_QueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SingleQueryResults_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SingleQueryResults_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_QueryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Usage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Usage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DescribeIndexStatsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DescribeIndexStatsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NamespaceSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NamespaceSummary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DescribeIndexStatsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DescribeIndexStatsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DescribeIndexStatsResponse_NamespacesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DescribeIndexStatsResponse_NamespacesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025db_data_2025-01.proto\032\034google/protobuf" +
      "/struct.proto\032\034google/api/annotations.pr" +
      "oto\032\037google/api/field_behavior.proto\"J\n\014" +
      "SparseValues\022\035\n\007indices\030\001 \003(\rB\003\340A\002R\007indi" +
      "ces\022\033\n\006values\030\002 \003(\002B\003\340A\002R\006values\"\236\001\n\006Vec" +
      "tor\022\023\n\002id\030\001 \001(\tB\003\340A\002R\002id\022\026\n\006values\030\002 \003(\002" +
      "R\006values\0222\n\rsparse_values\030\004 \001(\0132\r.Sparse" +
      "ValuesR\014sparseValues\0223\n\010metadata\030\003 \001(\0132\027" +
      ".google.protobuf.StructR\010metadata\"\272\001\n\014Sc" +
      "oredVector\022\023\n\002id\030\001 \001(\tB\003\340A\002R\002id\022\024\n\005score" +
      "\030\002 \001(\002R\005score\022\026\n\006values\030\003 \003(\002R\006values\0222\n" +
      "\rsparse_values\030\005 \001(\0132\r.SparseValuesR\014spa" +
      "rseValues\0223\n\010metadata\030\004 \001(\0132\027.google.pro" +
      "tobuf.StructR\010metadata\"\241\001\n\014RequestUnion\022" +
      "(\n\006upsert\030\001 \001(\0132\016.UpsertRequestH\000R\006upser" +
      "t\022(\n\006delete\030\002 \001(\0132\016.DeleteRequestH\000R\006del" +
      "ete\022(\n\006update\030\003 \001(\0132\016.UpdateRequestH\000R\006u" +
      "pdateB\023\n\021RequestUnionInner\"U\n\rUpsertRequ" +
      "est\022&\n\007vectors\030\001 \003(\0132\007.VectorB\003\340A\002R\007vect" +
      "ors\022\034\n\tnamespace\030\002 \001(\tR\tnamespace\"7\n\016Ups" +
      "ertResponse\022%\n\016upserted_count\030\001 \001(\rR\rups" +
      "ertedCount\"\217\001\n\rDeleteRequest\022\020\n\003ids\030\001 \003(" +
      "\tR\003ids\022\035\n\ndelete_all\030\002 \001(\010R\tdeleteAll\022\034\n" +
      "\tnamespace\030\003 \001(\tR\tnamespace\022/\n\006filter\030\004 " +
      "\001(\0132\027.google.protobuf.StructR\006filter\"\020\n\016" +
      "DeleteResponse\"C\n\014FetchRequest\022\025\n\003ids\030\001 " +
      "\003(\tB\003\340A\002R\003ids\022\034\n\tnamespace\030\002 \001(\tR\tnamesp" +
      "ace\"\326\001\n\rFetchResponse\0225\n\007vectors\030\001 \003(\0132\033" +
      ".FetchResponse.VectorsEntryR\007vectors\022\034\n\t" +
      "namespace\030\002 \001(\tR\tnamespace\022!\n\005usage\030\003 \001(" +
      "\0132\006.UsageH\000R\005usage\210\001\001\032C\n\014VectorsEntry\022\020\n" +
      "\003key\030\001 \001(\tR\003key\022\035\n\005value\030\002 \001(\0132\007.VectorR" +
      "\005value:\0028\001B\010\n\006_usage\"\275\001\n\013ListRequest\022\033\n\006" +
      "prefix\030\001 \001(\tH\000R\006prefix\210\001\001\022\031\n\005limit\030\002 \001(\r" +
      "H\001R\005limit\210\001\001\022.\n\020pagination_token\030\003 \001(\tH\002" +
      "R\017paginationToken\210\001\001\022\034\n\tnamespace\030\004 \001(\tR" +
      "\tnamespaceB\t\n\007_prefixB\010\n\006_limitB\023\n\021_pagi" +
      "nation_token\" \n\nPagination\022\022\n\004next\030\001 \001(\t" +
      "R\004next\"\032\n\010ListItem\022\016\n\002id\030\001 \001(\tR\002id\"\277\001\n\014L" +
      "istResponse\022#\n\007vectors\030\001 \003(\0132\t.ListItemR" +
      "\007vectors\0220\n\npagination\030\002 \001(\0132\013.Paginatio" +
      "nH\000R\npagination\210\001\001\022\034\n\tnamespace\030\003 \001(\tR\tn" +
      "amespace\022!\n\005usage\030\004 \001(\0132\006.UsageH\001R\005usage" +
      "\210\001\001B\r\n\013_paginationB\010\n\006_usage\"\275\001\n\013QueryVe" +
      "ctor\022\026\n\006values\030\001 \003(\002R\006values\0222\n\rsparse_v" +
      "alues\030\005 \001(\0132\r.SparseValuesR\014sparseValues" +
      "\022\023\n\005top_k\030\002 \001(\rR\004topK\022\034\n\tnamespace\030\003 \001(\t" +
      "R\tnamespace\022/\n\006filter\030\004 \001(\0132\027.google.pro" +
      "tobuf.StructR\006filter\"\321\002\n\014QueryRequest\022\034\n" +
      "\tnamespace\030\001 \001(\tR\tnamespace\022\030\n\005top_k\030\002 \001" +
      "(\rB\003\340A\002R\004topK\022/\n\006filter\030\003 \001(\0132\027.google.p" +
      "rotobuf.StructR\006filter\022%\n\016include_values" +
      "\030\004 \001(\010R\rincludeValues\022)\n\020include_metadat" +
      "a\030\005 \001(\010R\017includeMetadata\022*\n\007queries\030\006 \003(" +
      "\0132\014.QueryVectorB\002\030\001R\007queries\022\026\n\006vector\030\007" +
      " \003(\002R\006vector\0222\n\rsparse_vector\030\t \001(\0132\r.Sp" +
      "arseValuesR\014sparseVector\022\016\n\002id\030\010 \001(\tR\002id" +
      "\"[\n\022SingleQueryResults\022\'\n\007matches\030\001 \003(\0132" +
      "\r.ScoredVectorR\007matches\022\034\n\tnamespace\030\002 \001" +
      "(\tR\tnamespace\"\266\001\n\rQueryResponse\0221\n\007resul" +
      "ts\030\001 \003(\0132\023.SingleQueryResultsB\002\030\001R\007resul" +
      "ts\022\'\n\007matches\030\002 \003(\0132\r.ScoredVectorR\007matc" +
      "hes\022\034\n\tnamespace\030\003 \001(\tR\tnamespace\022!\n\005usa" +
      "ge\030\004 \001(\0132\006.UsageH\000R\005usage\210\001\001B\010\n\006_usage\":" +
      "\n\005Usage\022\"\n\nread_units\030\001 \001(\rH\000R\treadUnits" +
      "\210\001\001B\r\n\013_read_units\"\312\001\n\rUpdateRequest\022\023\n\002" +
      "id\030\001 \001(\tB\003\340A\002R\002id\022\026\n\006values\030\002 \003(\002R\006value" +
      "s\0222\n\rsparse_values\030\005 \001(\0132\r.SparseValuesR" +
      "\014sparseValues\022:\n\014set_metadata\030\003 \001(\0132\027.go" +
      "ogle.protobuf.StructR\013setMetadata\022\034\n\tnam" +
      "espace\030\004 \001(\tR\tnamespace\"\020\n\016UpdateRespons" +
      "e\"L\n\031DescribeIndexStatsRequest\022/\n\006filter" +
      "\030\001 \001(\0132\027.google.protobuf.StructR\006filter\"" +
      "5\n\020NamespaceSummary\022!\n\014vector_count\030\001 \001(" +
      "\rR\013vectorCount\"\237\003\n\032DescribeIndexStatsRes" +
      "ponse\022K\n\nnamespaces\030\001 \003(\0132+.DescribeInde" +
      "xStatsResponse.NamespacesEntryR\nnamespac" +
      "es\022!\n\tdimension\030\002 \001(\rH\000R\tdimension\210\001\001\022%\n" +
      "\016index_fullness\030\003 \001(\002R\rindexFullness\022,\n\022" +
      "total_vector_count\030\004 \001(\rR\020totalVectorCou" +
      "nt\022\033\n\006metric\030\005 \001(\tH\001R\006metric\210\001\001\022$\n\013vecto" +
      "r_type\030\006 \001(\tH\002R\nvectorType\210\001\001\032P\n\017Namespa" +
      "cesEntry\022\020\n\003key\030\001 \001(\tR\003key\022\'\n\005value\030\002 \001(" +
      "\0132\021.NamespaceSummaryR\005value:\0028\001B\014\n\n_dime" +
      "nsionB\t\n\007_metricB\016\n\014_vector_type2\271\004\n\rVec" +
      "torService\022E\n\006Upsert\022\016.UpsertRequest\032\017.U" +
      "psertResponse\"\032\202\323\344\223\002\024\"\017/vectors/upsert:\001" +
      "*\022X\n\006Delete\022\016.DeleteRequest\032\017.DeleteResp" +
      "onse\"-\202\323\344\223\002\'\"\017/vectors/delete:\001*Z\021*\017/vec" +
      "tors/delete\022>\n\005Fetch\022\r.FetchRequest\032\016.Fe" +
      "tchResponse\"\026\202\323\344\223\002\020\022\016/vectors/fetch\022:\n\004L" +
      "ist\022\014.ListRequest\032\r.ListResponse\"\025\202\323\344\223\002\017" +
      "\022\r/vectors/list\0229\n\005Query\022\r.QueryRequest\032" +
      "\016.QueryResponse\"\021\202\323\344\223\002\013\"\006/query:\001*\022E\n\006Up" +
      "date\022\016.UpdateRequest\032\017.UpdateResponse\"\032\202" +
      "\323\344\223\002\024\"\017/vectors/update:\001*\022\210\001\n\022DescribeIn" +
      "dexStats\022\032.DescribeIndexStatsRequest\032\033.D" +
      "escribeIndexStatsResponse\"9\202\323\344\223\0023\"\025/desc" +
      "ribe_index_stats:\001*Z\027\022\025/describe_index_s" +
      "tatsBS\n\021io.pinecone.protoP\001Z<github.com/" +
      "pinecone-io/go-pinecone/internal/gen/db_" +
      "data/grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
        });
    internal_static_SparseValues_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SparseValues_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SparseValues_descriptor,
        new java.lang.String[] { "Indices", "Values", });
    internal_static_Vector_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Vector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Vector_descriptor,
        new java.lang.String[] { "Id", "Values", "SparseValues", "Metadata", });
    internal_static_ScoredVector_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ScoredVector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ScoredVector_descriptor,
        new java.lang.String[] { "Id", "Score", "Values", "SparseValues", "Metadata", });
    internal_static_RequestUnion_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RequestUnion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RequestUnion_descriptor,
        new java.lang.String[] { "Upsert", "Delete", "Update", "RequestUnionInner", });
    internal_static_UpsertRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_UpsertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UpsertRequest_descriptor,
        new java.lang.String[] { "Vectors", "Namespace", });
    internal_static_UpsertResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_UpsertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UpsertResponse_descriptor,
        new java.lang.String[] { "UpsertedCount", });
    internal_static_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DeleteRequest_descriptor,
        new java.lang.String[] { "Ids", "DeleteAll", "Namespace", "Filter", });
    internal_static_DeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_DeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DeleteResponse_descriptor,
        new java.lang.String[] { });
    internal_static_FetchRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_FetchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FetchRequest_descriptor,
        new java.lang.String[] { "Ids", "Namespace", });
    internal_static_FetchResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_FetchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FetchResponse_descriptor,
        new java.lang.String[] { "Vectors", "Namespace", "Usage", });
    internal_static_FetchResponse_VectorsEntry_descriptor =
      internal_static_FetchResponse_descriptor.getNestedTypes().get(0);
    internal_static_FetchResponse_VectorsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FetchResponse_VectorsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ListRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_ListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ListRequest_descriptor,
        new java.lang.String[] { "Prefix", "Limit", "PaginationToken", "Namespace", });
    internal_static_Pagination_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_Pagination_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Pagination_descriptor,
        new java.lang.String[] { "Next", });
    internal_static_ListItem_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_ListItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ListItem_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_ListResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_ListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ListResponse_descriptor,
        new java.lang.String[] { "Vectors", "Pagination", "Namespace", "Usage", });
    internal_static_QueryVector_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_QueryVector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_QueryVector_descriptor,
        new java.lang.String[] { "Values", "SparseValues", "TopK", "Namespace", "Filter", });
    internal_static_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_QueryRequest_descriptor,
        new java.lang.String[] { "Namespace", "TopK", "Filter", "IncludeValues", "IncludeMetadata", "Queries", "Vector", "SparseVector", "Id", });
    internal_static_SingleQueryResults_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_SingleQueryResults_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SingleQueryResults_descriptor,
        new java.lang.String[] { "Matches", "Namespace", });
    internal_static_QueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_QueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_QueryResponse_descriptor,
        new java.lang.String[] { "Results", "Matches", "Namespace", "Usage", });
    internal_static_Usage_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_Usage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Usage_descriptor,
        new java.lang.String[] { "ReadUnits", });
    internal_static_UpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_UpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UpdateRequest_descriptor,
        new java.lang.String[] { "Id", "Values", "SparseValues", "SetMetadata", "Namespace", });
    internal_static_UpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_UpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UpdateResponse_descriptor,
        new java.lang.String[] { });
    internal_static_DescribeIndexStatsRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_DescribeIndexStatsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DescribeIndexStatsRequest_descriptor,
        new java.lang.String[] { "Filter", });
    internal_static_NamespaceSummary_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_NamespaceSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NamespaceSummary_descriptor,
        new java.lang.String[] { "VectorCount", });
    internal_static_DescribeIndexStatsResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_DescribeIndexStatsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DescribeIndexStatsResponse_descriptor,
        new java.lang.String[] { "Namespaces", "Dimension", "IndexFullness", "TotalVectorCount", "Metric", "VectorType", });
    internal_static_DescribeIndexStatsResponse_NamespacesEntry_descriptor =
      internal_static_DescribeIndexStatsResponse_descriptor.getNestedTypes().get(0);
    internal_static_DescribeIndexStatsResponse_NamespacesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DescribeIndexStatsResponse_NamespacesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
