// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector_service.proto

// Protobuf Java Version: 3.25.2
package io.pinecone.proto;

public interface FetchResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FetchResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The fetched vectors, in the form of a map between the fetched ids and the fetched vectors
   * </pre>
   *
   * <code>map&lt;string, .Vector&gt; vectors = 1;</code>
   */
  int getVectorsCount();
  /**
   * <pre>
   * The fetched vectors, in the form of a map between the fetched ids and the fetched vectors
   * </pre>
   *
   * <code>map&lt;string, .Vector&gt; vectors = 1;</code>
   */
  boolean containsVectors(
      String key);
  /**
   * Use {@link #getVectorsMap()} instead.
   */
  @Deprecated
  java.util.Map<String, Vector>
  getVectors();
  /**
   * <pre>
   * The fetched vectors, in the form of a map between the fetched ids and the fetched vectors
   * </pre>
   *
   * <code>map&lt;string, .Vector&gt; vectors = 1;</code>
   */
  java.util.Map<String, Vector>
  getVectorsMap();
  /**
   * <pre>
   * The fetched vectors, in the form of a map between the fetched ids and the fetched vectors
   * </pre>
   *
   * <code>map&lt;string, .Vector&gt; vectors = 1;</code>
   */
  /* nullable */
Vector getVectorsOrDefault(
      String key,
      /* nullable */
Vector defaultValue);
  /**
   * <pre>
   * The fetched vectors, in the form of a map between the fetched ids and the fetched vectors
   * </pre>
   *
   * <code>map&lt;string, .Vector&gt; vectors = 1;</code>
   */
  Vector getVectorsOrThrow(
      String key);

  /**
   * <pre>
   * The namespace of the vectors.
   * </pre>
   *
   * <code>string namespace = 2 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The namespace.
   */
  String getNamespace();
  /**
   * <pre>
   * The namespace of the vectors.
   * </pre>
   *
   * <code>string namespace = 2 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for namespace.
   */
  com.google.protobuf.ByteString
      getNamespaceBytes();

  /**
   * <pre>
   *  The usage for this operation.
   * </pre>
   *
   * <code>optional .Usage usage = 3 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the usage field is set.
   */
  boolean hasUsage();
  /**
   * <pre>
   *  The usage for this operation.
   * </pre>
   *
   * <code>optional .Usage usage = 3 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The usage.
   */
  Usage getUsage();
  /**
   * <pre>
   *  The usage for this operation.
   * </pre>
   *
   * <code>optional .Usage usage = 3 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  UsageOrBuilder getUsageOrBuilder();
}
