// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db_data_2025-04.proto
// Protobuf Java Version: 4.29.3

package io.pinecone.proto;

public interface ListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The vector IDs to fetch. Does not accept values containing spaces.
   * </pre>
   *
   * <code>optional string prefix = 1 [json_name = "prefix"];</code>
   * @return Whether the prefix field is set.
   */
  boolean hasPrefix();
  /**
   * <pre>
   * The vector IDs to fetch. Does not accept values containing spaces.
   * </pre>
   *
   * <code>optional string prefix = 1 [json_name = "prefix"];</code>
   * @return The prefix.
   */
  java.lang.String getPrefix();
  /**
   * <pre>
   * The vector IDs to fetch. Does not accept values containing spaces.
   * </pre>
   *
   * <code>optional string prefix = 1 [json_name = "prefix"];</code>
   * @return The bytes for prefix.
   */
  com.google.protobuf.ByteString
      getPrefixBytes();

  /**
   * <pre>
   * Max number of ids to return
   * </pre>
   *
   * <code>optional uint32 limit = 2 [json_name = "limit"];</code>
   * @return Whether the limit field is set.
   */
  boolean hasLimit();
  /**
   * <pre>
   * Max number of ids to return
   * </pre>
   *
   * <code>optional uint32 limit = 2 [json_name = "limit"];</code>
   * @return The limit.
   */
  int getLimit();

  /**
   * <pre>
   * Pagination token to continue a previous listing operation
   * </pre>
   *
   * <code>optional string pagination_token = 3 [json_name = "paginationToken"];</code>
   * @return Whether the paginationToken field is set.
   */
  boolean hasPaginationToken();
  /**
   * <pre>
   * Pagination token to continue a previous listing operation
   * </pre>
   *
   * <code>optional string pagination_token = 3 [json_name = "paginationToken"];</code>
   * @return The paginationToken.
   */
  java.lang.String getPaginationToken();
  /**
   * <pre>
   * Pagination token to continue a previous listing operation
   * </pre>
   *
   * <code>optional string pagination_token = 3 [json_name = "paginationToken"];</code>
   * @return The bytes for paginationToken.
   */
  com.google.protobuf.ByteString
      getPaginationTokenBytes();

  /**
   * <code>string namespace = 4 [json_name = "namespace"];</code>
   * @return The namespace.
   */
  java.lang.String getNamespace();
  /**
   * <code>string namespace = 4 [json_name = "namespace"];</code>
   * @return The bytes for namespace.
   */
  com.google.protobuf.ByteString
      getNamespaceBytes();
}
