// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector_service.proto

// Protobuf Java Version: 3.25.3
package io.pinecone.proto;

/**
 * <pre>
 * The response for the `List` operation.
 * </pre>
 *
 * Protobuf type {@code ListResponse}
 */
public final class ListResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ListResponse)
    ListResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListResponse.newBuilder() to construct.
  private ListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListResponse() {
    vectors_ = java.util.Collections.emptyList();
    namespace_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.pinecone.proto.VectorServiceOuterClass.internal_static_ListResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.pinecone.proto.VectorServiceOuterClass.internal_static_ListResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.pinecone.proto.ListResponse.class, io.pinecone.proto.ListResponse.Builder.class);
  }

  private int bitField0_;
  public static final int VECTORS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<io.pinecone.proto.ListItem> vectors_;
  /**
   * <pre>
   * A list of ids
   * </pre>
   *
   * <code>repeated .ListItem vectors = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.pinecone.proto.ListItem> getVectorsList() {
    return vectors_;
  }
  /**
   * <pre>
   * A list of ids
   * </pre>
   *
   * <code>repeated .ListItem vectors = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.pinecone.proto.ListItemOrBuilder> 
      getVectorsOrBuilderList() {
    return vectors_;
  }
  /**
   * <pre>
   * A list of ids
   * </pre>
   *
   * <code>repeated .ListItem vectors = 1;</code>
   */
  @java.lang.Override
  public int getVectorsCount() {
    return vectors_.size();
  }
  /**
   * <pre>
   * A list of ids
   * </pre>
   *
   * <code>repeated .ListItem vectors = 1;</code>
   */
  @java.lang.Override
  public io.pinecone.proto.ListItem getVectors(int index) {
    return vectors_.get(index);
  }
  /**
   * <pre>
   * A list of ids
   * </pre>
   *
   * <code>repeated .ListItem vectors = 1;</code>
   */
  @java.lang.Override
  public io.pinecone.proto.ListItemOrBuilder getVectorsOrBuilder(
      int index) {
    return vectors_.get(index);
  }

  public static final int PAGINATION_FIELD_NUMBER = 2;
  private io.pinecone.proto.Pagination pagination_;
  /**
   * <pre>
   * Pagination token to continue past this listing
   * </pre>
   *
   * <code>optional .Pagination pagination = 2;</code>
   * @return Whether the pagination field is set.
   */
  @java.lang.Override
  public boolean hasPagination() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Pagination token to continue past this listing
   * </pre>
   *
   * <code>optional .Pagination pagination = 2;</code>
   * @return The pagination.
   */
  @java.lang.Override
  public io.pinecone.proto.Pagination getPagination() {
    return pagination_ == null ? io.pinecone.proto.Pagination.getDefaultInstance() : pagination_;
  }
  /**
   * <pre>
   * Pagination token to continue past this listing
   * </pre>
   *
   * <code>optional .Pagination pagination = 2;</code>
   */
  @java.lang.Override
  public io.pinecone.proto.PaginationOrBuilder getPaginationOrBuilder() {
    return pagination_ == null ? io.pinecone.proto.Pagination.getDefaultInstance() : pagination_;
  }

  public static final int NAMESPACE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object namespace_ = "";
  /**
   * <pre>
   * The namespace of the vectors.
   * </pre>
   *
   * <code>string namespace = 3;</code>
   * @return The namespace.
   */
  @java.lang.Override
  public java.lang.String getNamespace() {
    java.lang.Object ref = namespace_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      namespace_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The namespace of the vectors.
   * </pre>
   *
   * <code>string namespace = 3;</code>
   * @return The bytes for namespace.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNamespaceBytes() {
    java.lang.Object ref = namespace_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      namespace_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USAGE_FIELD_NUMBER = 4;
  private io.pinecone.proto.Usage usage_;
  /**
   * <pre>
   *  The usage for this operation.
   * </pre>
   *
   * <code>optional .Usage usage = 4;</code>
   * @return Whether the usage field is set.
   */
  @java.lang.Override
  public boolean hasUsage() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   *  The usage for this operation.
   * </pre>
   *
   * <code>optional .Usage usage = 4;</code>
   * @return The usage.
   */
  @java.lang.Override
  public io.pinecone.proto.Usage getUsage() {
    return usage_ == null ? io.pinecone.proto.Usage.getDefaultInstance() : usage_;
  }
  /**
   * <pre>
   *  The usage for this operation.
   * </pre>
   *
   * <code>optional .Usage usage = 4;</code>
   */
  @java.lang.Override
  public io.pinecone.proto.UsageOrBuilder getUsageOrBuilder() {
    return usage_ == null ? io.pinecone.proto.Usage.getDefaultInstance() : usage_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < vectors_.size(); i++) {
      output.writeMessage(1, vectors_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getPagination());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(namespace_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, namespace_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(4, getUsage());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < vectors_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, vectors_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPagination());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(namespace_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, namespace_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getUsage());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.pinecone.proto.ListResponse)) {
      return super.equals(obj);
    }
    io.pinecone.proto.ListResponse other = (io.pinecone.proto.ListResponse) obj;

    if (!getVectorsList()
        .equals(other.getVectorsList())) return false;
    if (hasPagination() != other.hasPagination()) return false;
    if (hasPagination()) {
      if (!getPagination()
          .equals(other.getPagination())) return false;
    }
    if (!getNamespace()
        .equals(other.getNamespace())) return false;
    if (hasUsage() != other.hasUsage()) return false;
    if (hasUsage()) {
      if (!getUsage()
          .equals(other.getUsage())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getVectorsCount() > 0) {
      hash = (37 * hash) + VECTORS_FIELD_NUMBER;
      hash = (53 * hash) + getVectorsList().hashCode();
    }
    if (hasPagination()) {
      hash = (37 * hash) + PAGINATION_FIELD_NUMBER;
      hash = (53 * hash) + getPagination().hashCode();
    }
    hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
    hash = (53 * hash) + getNamespace().hashCode();
    if (hasUsage()) {
      hash = (37 * hash) + USAGE_FIELD_NUMBER;
      hash = (53 * hash) + getUsage().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.pinecone.proto.ListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pinecone.proto.ListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pinecone.proto.ListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pinecone.proto.ListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pinecone.proto.ListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pinecone.proto.ListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pinecone.proto.ListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.pinecone.proto.ListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.pinecone.proto.ListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.pinecone.proto.ListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.pinecone.proto.ListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.pinecone.proto.ListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.pinecone.proto.ListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The response for the `List` operation.
   * </pre>
   *
   * Protobuf type {@code ListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ListResponse)
      io.pinecone.proto.ListResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.pinecone.proto.VectorServiceOuterClass.internal_static_ListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.pinecone.proto.VectorServiceOuterClass.internal_static_ListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.pinecone.proto.ListResponse.class, io.pinecone.proto.ListResponse.Builder.class);
    }

    // Construct using io.pinecone.proto.ListResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getVectorsFieldBuilder();
        getPaginationFieldBuilder();
        getUsageFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (vectorsBuilder_ == null) {
        vectors_ = java.util.Collections.emptyList();
      } else {
        vectors_ = null;
        vectorsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      pagination_ = null;
      if (paginationBuilder_ != null) {
        paginationBuilder_.dispose();
        paginationBuilder_ = null;
      }
      namespace_ = "";
      usage_ = null;
      if (usageBuilder_ != null) {
        usageBuilder_.dispose();
        usageBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.pinecone.proto.VectorServiceOuterClass.internal_static_ListResponse_descriptor;
    }

    @java.lang.Override
    public io.pinecone.proto.ListResponse getDefaultInstanceForType() {
      return io.pinecone.proto.ListResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.pinecone.proto.ListResponse build() {
      io.pinecone.proto.ListResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.pinecone.proto.ListResponse buildPartial() {
      io.pinecone.proto.ListResponse result = new io.pinecone.proto.ListResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.pinecone.proto.ListResponse result) {
      if (vectorsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          vectors_ = java.util.Collections.unmodifiableList(vectors_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.vectors_ = vectors_;
      } else {
        result.vectors_ = vectorsBuilder_.build();
      }
    }

    private void buildPartial0(io.pinecone.proto.ListResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pagination_ = paginationBuilder_ == null
            ? pagination_
            : paginationBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.namespace_ = namespace_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.usage_ = usageBuilder_ == null
            ? usage_
            : usageBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.pinecone.proto.ListResponse) {
        return mergeFrom((io.pinecone.proto.ListResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.pinecone.proto.ListResponse other) {
      if (other == io.pinecone.proto.ListResponse.getDefaultInstance()) return this;
      if (vectorsBuilder_ == null) {
        if (!other.vectors_.isEmpty()) {
          if (vectors_.isEmpty()) {
            vectors_ = other.vectors_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureVectorsIsMutable();
            vectors_.addAll(other.vectors_);
          }
          onChanged();
        }
      } else {
        if (!other.vectors_.isEmpty()) {
          if (vectorsBuilder_.isEmpty()) {
            vectorsBuilder_.dispose();
            vectorsBuilder_ = null;
            vectors_ = other.vectors_;
            bitField0_ = (bitField0_ & ~0x00000001);
            vectorsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVectorsFieldBuilder() : null;
          } else {
            vectorsBuilder_.addAllMessages(other.vectors_);
          }
        }
      }
      if (other.hasPagination()) {
        mergePagination(other.getPagination());
      }
      if (!other.getNamespace().isEmpty()) {
        namespace_ = other.namespace_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasUsage()) {
        mergeUsage(other.getUsage());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.pinecone.proto.ListItem m =
                  input.readMessage(
                      io.pinecone.proto.ListItem.parser(),
                      extensionRegistry);
              if (vectorsBuilder_ == null) {
                ensureVectorsIsMutable();
                vectors_.add(m);
              } else {
                vectorsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getPaginationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              namespace_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getUsageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.pinecone.proto.ListItem> vectors_ =
      java.util.Collections.emptyList();
    private void ensureVectorsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        vectors_ = new java.util.ArrayList<io.pinecone.proto.ListItem>(vectors_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.pinecone.proto.ListItem, io.pinecone.proto.ListItem.Builder, io.pinecone.proto.ListItemOrBuilder> vectorsBuilder_;

    /**
     * <pre>
     * A list of ids
     * </pre>
     *
     * <code>repeated .ListItem vectors = 1;</code>
     */
    public java.util.List<io.pinecone.proto.ListItem> getVectorsList() {
      if (vectorsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(vectors_);
      } else {
        return vectorsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * A list of ids
     * </pre>
     *
     * <code>repeated .ListItem vectors = 1;</code>
     */
    public int getVectorsCount() {
      if (vectorsBuilder_ == null) {
        return vectors_.size();
      } else {
        return vectorsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * A list of ids
     * </pre>
     *
     * <code>repeated .ListItem vectors = 1;</code>
     */
    public io.pinecone.proto.ListItem getVectors(int index) {
      if (vectorsBuilder_ == null) {
        return vectors_.get(index);
      } else {
        return vectorsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * A list of ids
     * </pre>
     *
     * <code>repeated .ListItem vectors = 1;</code>
     */
    public Builder setVectors(
        int index, io.pinecone.proto.ListItem value) {
      if (vectorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVectorsIsMutable();
        vectors_.set(index, value);
        onChanged();
      } else {
        vectorsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of ids
     * </pre>
     *
     * <code>repeated .ListItem vectors = 1;</code>
     */
    public Builder setVectors(
        int index, io.pinecone.proto.ListItem.Builder builderForValue) {
      if (vectorsBuilder_ == null) {
        ensureVectorsIsMutable();
        vectors_.set(index, builderForValue.build());
        onChanged();
      } else {
        vectorsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of ids
     * </pre>
     *
     * <code>repeated .ListItem vectors = 1;</code>
     */
    public Builder addVectors(io.pinecone.proto.ListItem value) {
      if (vectorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVectorsIsMutable();
        vectors_.add(value);
        onChanged();
      } else {
        vectorsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of ids
     * </pre>
     *
     * <code>repeated .ListItem vectors = 1;</code>
     */
    public Builder addVectors(
        int index, io.pinecone.proto.ListItem value) {
      if (vectorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVectorsIsMutable();
        vectors_.add(index, value);
        onChanged();
      } else {
        vectorsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of ids
     * </pre>
     *
     * <code>repeated .ListItem vectors = 1;</code>
     */
    public Builder addVectors(
        io.pinecone.proto.ListItem.Builder builderForValue) {
      if (vectorsBuilder_ == null) {
        ensureVectorsIsMutable();
        vectors_.add(builderForValue.build());
        onChanged();
      } else {
        vectorsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of ids
     * </pre>
     *
     * <code>repeated .ListItem vectors = 1;</code>
     */
    public Builder addVectors(
        int index, io.pinecone.proto.ListItem.Builder builderForValue) {
      if (vectorsBuilder_ == null) {
        ensureVectorsIsMutable();
        vectors_.add(index, builderForValue.build());
        onChanged();
      } else {
        vectorsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of ids
     * </pre>
     *
     * <code>repeated .ListItem vectors = 1;</code>
     */
    public Builder addAllVectors(
        java.lang.Iterable<? extends io.pinecone.proto.ListItem> values) {
      if (vectorsBuilder_ == null) {
        ensureVectorsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, vectors_);
        onChanged();
      } else {
        vectorsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * A list of ids
     * </pre>
     *
     * <code>repeated .ListItem vectors = 1;</code>
     */
    public Builder clearVectors() {
      if (vectorsBuilder_ == null) {
        vectors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        vectorsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * A list of ids
     * </pre>
     *
     * <code>repeated .ListItem vectors = 1;</code>
     */
    public Builder removeVectors(int index) {
      if (vectorsBuilder_ == null) {
        ensureVectorsIsMutable();
        vectors_.remove(index);
        onChanged();
      } else {
        vectorsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * A list of ids
     * </pre>
     *
     * <code>repeated .ListItem vectors = 1;</code>
     */
    public io.pinecone.proto.ListItem.Builder getVectorsBuilder(
        int index) {
      return getVectorsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * A list of ids
     * </pre>
     *
     * <code>repeated .ListItem vectors = 1;</code>
     */
    public io.pinecone.proto.ListItemOrBuilder getVectorsOrBuilder(
        int index) {
      if (vectorsBuilder_ == null) {
        return vectors_.get(index);  } else {
        return vectorsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * A list of ids
     * </pre>
     *
     * <code>repeated .ListItem vectors = 1;</code>
     */
    public java.util.List<? extends io.pinecone.proto.ListItemOrBuilder> 
         getVectorsOrBuilderList() {
      if (vectorsBuilder_ != null) {
        return vectorsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(vectors_);
      }
    }
    /**
     * <pre>
     * A list of ids
     * </pre>
     *
     * <code>repeated .ListItem vectors = 1;</code>
     */
    public io.pinecone.proto.ListItem.Builder addVectorsBuilder() {
      return getVectorsFieldBuilder().addBuilder(
          io.pinecone.proto.ListItem.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of ids
     * </pre>
     *
     * <code>repeated .ListItem vectors = 1;</code>
     */
    public io.pinecone.proto.ListItem.Builder addVectorsBuilder(
        int index) {
      return getVectorsFieldBuilder().addBuilder(
          index, io.pinecone.proto.ListItem.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of ids
     * </pre>
     *
     * <code>repeated .ListItem vectors = 1;</code>
     */
    public java.util.List<io.pinecone.proto.ListItem.Builder> 
         getVectorsBuilderList() {
      return getVectorsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.pinecone.proto.ListItem, io.pinecone.proto.ListItem.Builder, io.pinecone.proto.ListItemOrBuilder> 
        getVectorsFieldBuilder() {
      if (vectorsBuilder_ == null) {
        vectorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.pinecone.proto.ListItem, io.pinecone.proto.ListItem.Builder, io.pinecone.proto.ListItemOrBuilder>(
                vectors_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        vectors_ = null;
      }
      return vectorsBuilder_;
    }

    private io.pinecone.proto.Pagination pagination_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.pinecone.proto.Pagination, io.pinecone.proto.Pagination.Builder, io.pinecone.proto.PaginationOrBuilder> paginationBuilder_;
    /**
     * <pre>
     * Pagination token to continue past this listing
     * </pre>
     *
     * <code>optional .Pagination pagination = 2;</code>
     * @return Whether the pagination field is set.
     */
    public boolean hasPagination() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Pagination token to continue past this listing
     * </pre>
     *
     * <code>optional .Pagination pagination = 2;</code>
     * @return The pagination.
     */
    public io.pinecone.proto.Pagination getPagination() {
      if (paginationBuilder_ == null) {
        return pagination_ == null ? io.pinecone.proto.Pagination.getDefaultInstance() : pagination_;
      } else {
        return paginationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Pagination token to continue past this listing
     * </pre>
     *
     * <code>optional .Pagination pagination = 2;</code>
     */
    public Builder setPagination(io.pinecone.proto.Pagination value) {
      if (paginationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pagination_ = value;
      } else {
        paginationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pagination token to continue past this listing
     * </pre>
     *
     * <code>optional .Pagination pagination = 2;</code>
     */
    public Builder setPagination(
        io.pinecone.proto.Pagination.Builder builderForValue) {
      if (paginationBuilder_ == null) {
        pagination_ = builderForValue.build();
      } else {
        paginationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pagination token to continue past this listing
     * </pre>
     *
     * <code>optional .Pagination pagination = 2;</code>
     */
    public Builder mergePagination(io.pinecone.proto.Pagination value) {
      if (paginationBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          pagination_ != null &&
          pagination_ != io.pinecone.proto.Pagination.getDefaultInstance()) {
          getPaginationBuilder().mergeFrom(value);
        } else {
          pagination_ = value;
        }
      } else {
        paginationBuilder_.mergeFrom(value);
      }
      if (pagination_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Pagination token to continue past this listing
     * </pre>
     *
     * <code>optional .Pagination pagination = 2;</code>
     */
    public Builder clearPagination() {
      bitField0_ = (bitField0_ & ~0x00000002);
      pagination_ = null;
      if (paginationBuilder_ != null) {
        paginationBuilder_.dispose();
        paginationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pagination token to continue past this listing
     * </pre>
     *
     * <code>optional .Pagination pagination = 2;</code>
     */
    public io.pinecone.proto.Pagination.Builder getPaginationBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getPaginationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Pagination token to continue past this listing
     * </pre>
     *
     * <code>optional .Pagination pagination = 2;</code>
     */
    public io.pinecone.proto.PaginationOrBuilder getPaginationOrBuilder() {
      if (paginationBuilder_ != null) {
        return paginationBuilder_.getMessageOrBuilder();
      } else {
        return pagination_ == null ?
            io.pinecone.proto.Pagination.getDefaultInstance() : pagination_;
      }
    }
    /**
     * <pre>
     * Pagination token to continue past this listing
     * </pre>
     *
     * <code>optional .Pagination pagination = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.pinecone.proto.Pagination, io.pinecone.proto.Pagination.Builder, io.pinecone.proto.PaginationOrBuilder> 
        getPaginationFieldBuilder() {
      if (paginationBuilder_ == null) {
        paginationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.pinecone.proto.Pagination, io.pinecone.proto.Pagination.Builder, io.pinecone.proto.PaginationOrBuilder>(
                getPagination(),
                getParentForChildren(),
                isClean());
        pagination_ = null;
      }
      return paginationBuilder_;
    }

    private java.lang.Object namespace_ = "";
    /**
     * <pre>
     * The namespace of the vectors.
     * </pre>
     *
     * <code>string namespace = 3;</code>
     * @return The namespace.
     */
    public java.lang.String getNamespace() {
      java.lang.Object ref = namespace_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        namespace_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The namespace of the vectors.
     * </pre>
     *
     * <code>string namespace = 3;</code>
     * @return The bytes for namespace.
     */
    public com.google.protobuf.ByteString
        getNamespaceBytes() {
      java.lang.Object ref = namespace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        namespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The namespace of the vectors.
     * </pre>
     *
     * <code>string namespace = 3;</code>
     * @param value The namespace to set.
     * @return This builder for chaining.
     */
    public Builder setNamespace(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      namespace_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The namespace of the vectors.
     * </pre>
     *
     * <code>string namespace = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNamespace() {
      namespace_ = getDefaultInstance().getNamespace();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The namespace of the vectors.
     * </pre>
     *
     * <code>string namespace = 3;</code>
     * @param value The bytes for namespace to set.
     * @return This builder for chaining.
     */
    public Builder setNamespaceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      namespace_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private io.pinecone.proto.Usage usage_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.pinecone.proto.Usage, io.pinecone.proto.Usage.Builder, io.pinecone.proto.UsageOrBuilder> usageBuilder_;
    /**
     * <pre>
     *  The usage for this operation.
     * </pre>
     *
     * <code>optional .Usage usage = 4;</code>
     * @return Whether the usage field is set.
     */
    public boolean hasUsage() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     *  The usage for this operation.
     * </pre>
     *
     * <code>optional .Usage usage = 4;</code>
     * @return The usage.
     */
    public io.pinecone.proto.Usage getUsage() {
      if (usageBuilder_ == null) {
        return usage_ == null ? io.pinecone.proto.Usage.getDefaultInstance() : usage_;
      } else {
        return usageBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *  The usage for this operation.
     * </pre>
     *
     * <code>optional .Usage usage = 4;</code>
     */
    public Builder setUsage(io.pinecone.proto.Usage value) {
      if (usageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        usage_ = value;
      } else {
        usageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  The usage for this operation.
     * </pre>
     *
     * <code>optional .Usage usage = 4;</code>
     */
    public Builder setUsage(
        io.pinecone.proto.Usage.Builder builderForValue) {
      if (usageBuilder_ == null) {
        usage_ = builderForValue.build();
      } else {
        usageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  The usage for this operation.
     * </pre>
     *
     * <code>optional .Usage usage = 4;</code>
     */
    public Builder mergeUsage(io.pinecone.proto.Usage value) {
      if (usageBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          usage_ != null &&
          usage_ != io.pinecone.proto.Usage.getDefaultInstance()) {
          getUsageBuilder().mergeFrom(value);
        } else {
          usage_ = value;
        }
      } else {
        usageBuilder_.mergeFrom(value);
      }
      if (usage_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     *  The usage for this operation.
     * </pre>
     *
     * <code>optional .Usage usage = 4;</code>
     */
    public Builder clearUsage() {
      bitField0_ = (bitField0_ & ~0x00000008);
      usage_ = null;
      if (usageBuilder_ != null) {
        usageBuilder_.dispose();
        usageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  The usage for this operation.
     * </pre>
     *
     * <code>optional .Usage usage = 4;</code>
     */
    public io.pinecone.proto.Usage.Builder getUsageBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getUsageFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *  The usage for this operation.
     * </pre>
     *
     * <code>optional .Usage usage = 4;</code>
     */
    public io.pinecone.proto.UsageOrBuilder getUsageOrBuilder() {
      if (usageBuilder_ != null) {
        return usageBuilder_.getMessageOrBuilder();
      } else {
        return usage_ == null ?
            io.pinecone.proto.Usage.getDefaultInstance() : usage_;
      }
    }
    /**
     * <pre>
     *  The usage for this operation.
     * </pre>
     *
     * <code>optional .Usage usage = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.pinecone.proto.Usage, io.pinecone.proto.Usage.Builder, io.pinecone.proto.UsageOrBuilder> 
        getUsageFieldBuilder() {
      if (usageBuilder_ == null) {
        usageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.pinecone.proto.Usage, io.pinecone.proto.Usage.Builder, io.pinecone.proto.UsageOrBuilder>(
                getUsage(),
                getParentForChildren(),
                isClean());
        usage_ = null;
      }
      return usageBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ListResponse)
  }

  // @@protoc_insertion_point(class_scope:ListResponse)
  private static final io.pinecone.proto.ListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.pinecone.proto.ListResponse();
  }

  public static io.pinecone.proto.ListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListResponse>() {
    @java.lang.Override
    public ListResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.pinecone.proto.ListResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

