// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db_data_2025-04.proto
// Protobuf Java Version: 4.29.3

package io.pinecone.proto;

/**
 * <pre>
 * A summary of the contents of a namespace.
 * </pre>
 *
 * Protobuf type {@code NamespaceSummary}
 */
public final class NamespaceSummary extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:NamespaceSummary)
    NamespaceSummaryOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      NamespaceSummary.class.getName());
  }
  // Use NamespaceSummary.newBuilder() to construct.
  private NamespaceSummary(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private NamespaceSummary() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.pinecone.proto.DbData202504.internal_static_NamespaceSummary_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.pinecone.proto.DbData202504.internal_static_NamespaceSummary_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.pinecone.proto.NamespaceSummary.class, io.pinecone.proto.NamespaceSummary.Builder.class);
  }

  public static final int VECTOR_COUNT_FIELD_NUMBER = 1;
  private int vectorCount_ = 0;
  /**
   * <pre>
   * The number of vectors stored in this namespace. Note that updates to this field may lag behind updates to the
   * underlying index and corresponding query results, etc.
   * </pre>
   *
   * <code>uint32 vector_count = 1 [json_name = "vectorCount"];</code>
   * @return The vectorCount.
   */
  @java.lang.Override
  public int getVectorCount() {
    return vectorCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (vectorCount_ != 0) {
      output.writeUInt32(1, vectorCount_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (vectorCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, vectorCount_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.pinecone.proto.NamespaceSummary)) {
      return super.equals(obj);
    }
    io.pinecone.proto.NamespaceSummary other = (io.pinecone.proto.NamespaceSummary) obj;

    if (getVectorCount()
        != other.getVectorCount()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VECTOR_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getVectorCount();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.pinecone.proto.NamespaceSummary parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pinecone.proto.NamespaceSummary parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pinecone.proto.NamespaceSummary parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pinecone.proto.NamespaceSummary parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pinecone.proto.NamespaceSummary parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pinecone.proto.NamespaceSummary parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pinecone.proto.NamespaceSummary parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.pinecone.proto.NamespaceSummary parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.pinecone.proto.NamespaceSummary parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.pinecone.proto.NamespaceSummary parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.pinecone.proto.NamespaceSummary parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.pinecone.proto.NamespaceSummary parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.pinecone.proto.NamespaceSummary prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A summary of the contents of a namespace.
   * </pre>
   *
   * Protobuf type {@code NamespaceSummary}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:NamespaceSummary)
      io.pinecone.proto.NamespaceSummaryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.pinecone.proto.DbData202504.internal_static_NamespaceSummary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.pinecone.proto.DbData202504.internal_static_NamespaceSummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.pinecone.proto.NamespaceSummary.class, io.pinecone.proto.NamespaceSummary.Builder.class);
    }

    // Construct using io.pinecone.proto.NamespaceSummary.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      vectorCount_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.pinecone.proto.DbData202504.internal_static_NamespaceSummary_descriptor;
    }

    @java.lang.Override
    public io.pinecone.proto.NamespaceSummary getDefaultInstanceForType() {
      return io.pinecone.proto.NamespaceSummary.getDefaultInstance();
    }

    @java.lang.Override
    public io.pinecone.proto.NamespaceSummary build() {
      io.pinecone.proto.NamespaceSummary result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.pinecone.proto.NamespaceSummary buildPartial() {
      io.pinecone.proto.NamespaceSummary result = new io.pinecone.proto.NamespaceSummary(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.pinecone.proto.NamespaceSummary result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.vectorCount_ = vectorCount_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.pinecone.proto.NamespaceSummary) {
        return mergeFrom((io.pinecone.proto.NamespaceSummary)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.pinecone.proto.NamespaceSummary other) {
      if (other == io.pinecone.proto.NamespaceSummary.getDefaultInstance()) return this;
      if (other.getVectorCount() != 0) {
        setVectorCount(other.getVectorCount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              vectorCount_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int vectorCount_ ;
    /**
     * <pre>
     * The number of vectors stored in this namespace. Note that updates to this field may lag behind updates to the
     * underlying index and corresponding query results, etc.
     * </pre>
     *
     * <code>uint32 vector_count = 1 [json_name = "vectorCount"];</code>
     * @return The vectorCount.
     */
    @java.lang.Override
    public int getVectorCount() {
      return vectorCount_;
    }
    /**
     * <pre>
     * The number of vectors stored in this namespace. Note that updates to this field may lag behind updates to the
     * underlying index and corresponding query results, etc.
     * </pre>
     *
     * <code>uint32 vector_count = 1 [json_name = "vectorCount"];</code>
     * @param value The vectorCount to set.
     * @return This builder for chaining.
     */
    public Builder setVectorCount(int value) {

      vectorCount_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The number of vectors stored in this namespace. Note that updates to this field may lag behind updates to the
     * underlying index and corresponding query results, etc.
     * </pre>
     *
     * <code>uint32 vector_count = 1 [json_name = "vectorCount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearVectorCount() {
      bitField0_ = (bitField0_ & ~0x00000001);
      vectorCount_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:NamespaceSummary)
  }

  // @@protoc_insertion_point(class_scope:NamespaceSummary)
  private static final io.pinecone.proto.NamespaceSummary DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.pinecone.proto.NamespaceSummary();
  }

  public static io.pinecone.proto.NamespaceSummary getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NamespaceSummary>
      PARSER = new com.google.protobuf.AbstractParser<NamespaceSummary>() {
    @java.lang.Override
    public NamespaceSummary parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NamespaceSummary> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NamespaceSummary> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.pinecone.proto.NamespaceSummary getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

