// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db_data_2025-10.proto
// Protobuf Java Version: 4.29.3

package io.pinecone.proto;

/**
 * Protobuf type {@code NamespaceDescription}
 */
public final class NamespaceDescription extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:NamespaceDescription)
    NamespaceDescriptionOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      NamespaceDescription.class.getName());
  }
  // Use NamespaceDescription.newBuilder() to construct.
  private NamespaceDescription(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private NamespaceDescription() {
    name_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.pinecone.proto.DbData202510.internal_static_NamespaceDescription_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.pinecone.proto.DbData202510.internal_static_NamespaceDescription_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.pinecone.proto.NamespaceDescription.class, io.pinecone.proto.NamespaceDescription.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECORD_COUNT_FIELD_NUMBER = 2;
  private long recordCount_ = 0L;
  /**
   * <code>uint64 record_count = 2 [json_name = "recordCount"];</code>
   * @return The recordCount.
   */
  @java.lang.Override
  public long getRecordCount() {
    return recordCount_;
  }

  public static final int SCHEMA_FIELD_NUMBER = 3;
  private io.pinecone.proto.MetadataSchema schema_;
  /**
   * <code>optional .MetadataSchema schema = 3 [json_name = "schema"];</code>
   * @return Whether the schema field is set.
   */
  @java.lang.Override
  public boolean hasSchema() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .MetadataSchema schema = 3 [json_name = "schema"];</code>
   * @return The schema.
   */
  @java.lang.Override
  public io.pinecone.proto.MetadataSchema getSchema() {
    return schema_ == null ? io.pinecone.proto.MetadataSchema.getDefaultInstance() : schema_;
  }
  /**
   * <code>optional .MetadataSchema schema = 3 [json_name = "schema"];</code>
   */
  @java.lang.Override
  public io.pinecone.proto.MetadataSchemaOrBuilder getSchemaOrBuilder() {
    return schema_ == null ? io.pinecone.proto.MetadataSchema.getDefaultInstance() : schema_;
  }

  public static final int INDEXED_FIELDS_FIELD_NUMBER = 4;
  private io.pinecone.proto.IndexedFields indexedFields_;
  /**
   * <pre>
   * List of indexed fields in the namespace
   * </pre>
   *
   * <code>optional .IndexedFields indexed_fields = 4 [json_name = "indexedFields"];</code>
   * @return Whether the indexedFields field is set.
   */
  @java.lang.Override
  public boolean hasIndexedFields() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * List of indexed fields in the namespace
   * </pre>
   *
   * <code>optional .IndexedFields indexed_fields = 4 [json_name = "indexedFields"];</code>
   * @return The indexedFields.
   */
  @java.lang.Override
  public io.pinecone.proto.IndexedFields getIndexedFields() {
    return indexedFields_ == null ? io.pinecone.proto.IndexedFields.getDefaultInstance() : indexedFields_;
  }
  /**
   * <pre>
   * List of indexed fields in the namespace
   * </pre>
   *
   * <code>optional .IndexedFields indexed_fields = 4 [json_name = "indexedFields"];</code>
   */
  @java.lang.Override
  public io.pinecone.proto.IndexedFieldsOrBuilder getIndexedFieldsOrBuilder() {
    return indexedFields_ == null ? io.pinecone.proto.IndexedFields.getDefaultInstance() : indexedFields_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (recordCount_ != 0L) {
      output.writeUInt64(2, recordCount_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getSchema());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(4, getIndexedFields());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (recordCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, recordCount_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSchema());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getIndexedFields());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.pinecone.proto.NamespaceDescription)) {
      return super.equals(obj);
    }
    io.pinecone.proto.NamespaceDescription other = (io.pinecone.proto.NamespaceDescription) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (getRecordCount()
        != other.getRecordCount()) return false;
    if (hasSchema() != other.hasSchema()) return false;
    if (hasSchema()) {
      if (!getSchema()
          .equals(other.getSchema())) return false;
    }
    if (hasIndexedFields() != other.hasIndexedFields()) return false;
    if (hasIndexedFields()) {
      if (!getIndexedFields()
          .equals(other.getIndexedFields())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + RECORD_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRecordCount());
    if (hasSchema()) {
      hash = (37 * hash) + SCHEMA_FIELD_NUMBER;
      hash = (53 * hash) + getSchema().hashCode();
    }
    if (hasIndexedFields()) {
      hash = (37 * hash) + INDEXED_FIELDS_FIELD_NUMBER;
      hash = (53 * hash) + getIndexedFields().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.pinecone.proto.NamespaceDescription parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pinecone.proto.NamespaceDescription parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pinecone.proto.NamespaceDescription parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pinecone.proto.NamespaceDescription parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pinecone.proto.NamespaceDescription parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pinecone.proto.NamespaceDescription parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pinecone.proto.NamespaceDescription parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.pinecone.proto.NamespaceDescription parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.pinecone.proto.NamespaceDescription parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.pinecone.proto.NamespaceDescription parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.pinecone.proto.NamespaceDescription parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.pinecone.proto.NamespaceDescription parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.pinecone.proto.NamespaceDescription prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code NamespaceDescription}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:NamespaceDescription)
      io.pinecone.proto.NamespaceDescriptionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.pinecone.proto.DbData202510.internal_static_NamespaceDescription_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.pinecone.proto.DbData202510.internal_static_NamespaceDescription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.pinecone.proto.NamespaceDescription.class, io.pinecone.proto.NamespaceDescription.Builder.class);
    }

    // Construct using io.pinecone.proto.NamespaceDescription.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getSchemaFieldBuilder();
        getIndexedFieldsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      recordCount_ = 0L;
      schema_ = null;
      if (schemaBuilder_ != null) {
        schemaBuilder_.dispose();
        schemaBuilder_ = null;
      }
      indexedFields_ = null;
      if (indexedFieldsBuilder_ != null) {
        indexedFieldsBuilder_.dispose();
        indexedFieldsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.pinecone.proto.DbData202510.internal_static_NamespaceDescription_descriptor;
    }

    @java.lang.Override
    public io.pinecone.proto.NamespaceDescription getDefaultInstanceForType() {
      return io.pinecone.proto.NamespaceDescription.getDefaultInstance();
    }

    @java.lang.Override
    public io.pinecone.proto.NamespaceDescription build() {
      io.pinecone.proto.NamespaceDescription result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.pinecone.proto.NamespaceDescription buildPartial() {
      io.pinecone.proto.NamespaceDescription result = new io.pinecone.proto.NamespaceDescription(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.pinecone.proto.NamespaceDescription result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.recordCount_ = recordCount_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.schema_ = schemaBuilder_ == null
            ? schema_
            : schemaBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.indexedFields_ = indexedFieldsBuilder_ == null
            ? indexedFields_
            : indexedFieldsBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.pinecone.proto.NamespaceDescription) {
        return mergeFrom((io.pinecone.proto.NamespaceDescription)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.pinecone.proto.NamespaceDescription other) {
      if (other == io.pinecone.proto.NamespaceDescription.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getRecordCount() != 0L) {
        setRecordCount(other.getRecordCount());
      }
      if (other.hasSchema()) {
        mergeSchema(other.getSchema());
      }
      if (other.hasIndexedFields()) {
        mergeIndexedFields(other.getIndexedFields());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              recordCount_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getSchemaFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getIndexedFieldsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long recordCount_ ;
    /**
     * <code>uint64 record_count = 2 [json_name = "recordCount"];</code>
     * @return The recordCount.
     */
    @java.lang.Override
    public long getRecordCount() {
      return recordCount_;
    }
    /**
     * <code>uint64 record_count = 2 [json_name = "recordCount"];</code>
     * @param value The recordCount to set.
     * @return This builder for chaining.
     */
    public Builder setRecordCount(long value) {

      recordCount_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 record_count = 2 [json_name = "recordCount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRecordCount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      recordCount_ = 0L;
      onChanged();
      return this;
    }

    private io.pinecone.proto.MetadataSchema schema_;
    private com.google.protobuf.SingleFieldBuilder<
        io.pinecone.proto.MetadataSchema, io.pinecone.proto.MetadataSchema.Builder, io.pinecone.proto.MetadataSchemaOrBuilder> schemaBuilder_;
    /**
     * <code>optional .MetadataSchema schema = 3 [json_name = "schema"];</code>
     * @return Whether the schema field is set.
     */
    public boolean hasSchema() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .MetadataSchema schema = 3 [json_name = "schema"];</code>
     * @return The schema.
     */
    public io.pinecone.proto.MetadataSchema getSchema() {
      if (schemaBuilder_ == null) {
        return schema_ == null ? io.pinecone.proto.MetadataSchema.getDefaultInstance() : schema_;
      } else {
        return schemaBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .MetadataSchema schema = 3 [json_name = "schema"];</code>
     */
    public Builder setSchema(io.pinecone.proto.MetadataSchema value) {
      if (schemaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        schema_ = value;
      } else {
        schemaBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .MetadataSchema schema = 3 [json_name = "schema"];</code>
     */
    public Builder setSchema(
        io.pinecone.proto.MetadataSchema.Builder builderForValue) {
      if (schemaBuilder_ == null) {
        schema_ = builderForValue.build();
      } else {
        schemaBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .MetadataSchema schema = 3 [json_name = "schema"];</code>
     */
    public Builder mergeSchema(io.pinecone.proto.MetadataSchema value) {
      if (schemaBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          schema_ != null &&
          schema_ != io.pinecone.proto.MetadataSchema.getDefaultInstance()) {
          getSchemaBuilder().mergeFrom(value);
        } else {
          schema_ = value;
        }
      } else {
        schemaBuilder_.mergeFrom(value);
      }
      if (schema_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .MetadataSchema schema = 3 [json_name = "schema"];</code>
     */
    public Builder clearSchema() {
      bitField0_ = (bitField0_ & ~0x00000004);
      schema_ = null;
      if (schemaBuilder_ != null) {
        schemaBuilder_.dispose();
        schemaBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .MetadataSchema schema = 3 [json_name = "schema"];</code>
     */
    public io.pinecone.proto.MetadataSchema.Builder getSchemaBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getSchemaFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .MetadataSchema schema = 3 [json_name = "schema"];</code>
     */
    public io.pinecone.proto.MetadataSchemaOrBuilder getSchemaOrBuilder() {
      if (schemaBuilder_ != null) {
        return schemaBuilder_.getMessageOrBuilder();
      } else {
        return schema_ == null ?
            io.pinecone.proto.MetadataSchema.getDefaultInstance() : schema_;
      }
    }
    /**
     * <code>optional .MetadataSchema schema = 3 [json_name = "schema"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.pinecone.proto.MetadataSchema, io.pinecone.proto.MetadataSchema.Builder, io.pinecone.proto.MetadataSchemaOrBuilder> 
        getSchemaFieldBuilder() {
      if (schemaBuilder_ == null) {
        schemaBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.pinecone.proto.MetadataSchema, io.pinecone.proto.MetadataSchema.Builder, io.pinecone.proto.MetadataSchemaOrBuilder>(
                getSchema(),
                getParentForChildren(),
                isClean());
        schema_ = null;
      }
      return schemaBuilder_;
    }

    private io.pinecone.proto.IndexedFields indexedFields_;
    private com.google.protobuf.SingleFieldBuilder<
        io.pinecone.proto.IndexedFields, io.pinecone.proto.IndexedFields.Builder, io.pinecone.proto.IndexedFieldsOrBuilder> indexedFieldsBuilder_;
    /**
     * <pre>
     * List of indexed fields in the namespace
     * </pre>
     *
     * <code>optional .IndexedFields indexed_fields = 4 [json_name = "indexedFields"];</code>
     * @return Whether the indexedFields field is set.
     */
    public boolean hasIndexedFields() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * List of indexed fields in the namespace
     * </pre>
     *
     * <code>optional .IndexedFields indexed_fields = 4 [json_name = "indexedFields"];</code>
     * @return The indexedFields.
     */
    public io.pinecone.proto.IndexedFields getIndexedFields() {
      if (indexedFieldsBuilder_ == null) {
        return indexedFields_ == null ? io.pinecone.proto.IndexedFields.getDefaultInstance() : indexedFields_;
      } else {
        return indexedFieldsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * List of indexed fields in the namespace
     * </pre>
     *
     * <code>optional .IndexedFields indexed_fields = 4 [json_name = "indexedFields"];</code>
     */
    public Builder setIndexedFields(io.pinecone.proto.IndexedFields value) {
      if (indexedFieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        indexedFields_ = value;
      } else {
        indexedFieldsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of indexed fields in the namespace
     * </pre>
     *
     * <code>optional .IndexedFields indexed_fields = 4 [json_name = "indexedFields"];</code>
     */
    public Builder setIndexedFields(
        io.pinecone.proto.IndexedFields.Builder builderForValue) {
      if (indexedFieldsBuilder_ == null) {
        indexedFields_ = builderForValue.build();
      } else {
        indexedFieldsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of indexed fields in the namespace
     * </pre>
     *
     * <code>optional .IndexedFields indexed_fields = 4 [json_name = "indexedFields"];</code>
     */
    public Builder mergeIndexedFields(io.pinecone.proto.IndexedFields value) {
      if (indexedFieldsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          indexedFields_ != null &&
          indexedFields_ != io.pinecone.proto.IndexedFields.getDefaultInstance()) {
          getIndexedFieldsBuilder().mergeFrom(value);
        } else {
          indexedFields_ = value;
        }
      } else {
        indexedFieldsBuilder_.mergeFrom(value);
      }
      if (indexedFields_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * List of indexed fields in the namespace
     * </pre>
     *
     * <code>optional .IndexedFields indexed_fields = 4 [json_name = "indexedFields"];</code>
     */
    public Builder clearIndexedFields() {
      bitField0_ = (bitField0_ & ~0x00000008);
      indexedFields_ = null;
      if (indexedFieldsBuilder_ != null) {
        indexedFieldsBuilder_.dispose();
        indexedFieldsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of indexed fields in the namespace
     * </pre>
     *
     * <code>optional .IndexedFields indexed_fields = 4 [json_name = "indexedFields"];</code>
     */
    public io.pinecone.proto.IndexedFields.Builder getIndexedFieldsBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getIndexedFieldsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * List of indexed fields in the namespace
     * </pre>
     *
     * <code>optional .IndexedFields indexed_fields = 4 [json_name = "indexedFields"];</code>
     */
    public io.pinecone.proto.IndexedFieldsOrBuilder getIndexedFieldsOrBuilder() {
      if (indexedFieldsBuilder_ != null) {
        return indexedFieldsBuilder_.getMessageOrBuilder();
      } else {
        return indexedFields_ == null ?
            io.pinecone.proto.IndexedFields.getDefaultInstance() : indexedFields_;
      }
    }
    /**
     * <pre>
     * List of indexed fields in the namespace
     * </pre>
     *
     * <code>optional .IndexedFields indexed_fields = 4 [json_name = "indexedFields"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.pinecone.proto.IndexedFields, io.pinecone.proto.IndexedFields.Builder, io.pinecone.proto.IndexedFieldsOrBuilder> 
        getIndexedFieldsFieldBuilder() {
      if (indexedFieldsBuilder_ == null) {
        indexedFieldsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.pinecone.proto.IndexedFields, io.pinecone.proto.IndexedFields.Builder, io.pinecone.proto.IndexedFieldsOrBuilder>(
                getIndexedFields(),
                getParentForChildren(),
                isClean());
        indexedFields_ = null;
      }
      return indexedFieldsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:NamespaceDescription)
  }

  // @@protoc_insertion_point(class_scope:NamespaceDescription)
  private static final io.pinecone.proto.NamespaceDescription DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.pinecone.proto.NamespaceDescription();
  }

  public static io.pinecone.proto.NamespaceDescription getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NamespaceDescription>
      PARSER = new com.google.protobuf.AbstractParser<NamespaceDescription>() {
    @java.lang.Override
    public NamespaceDescription parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NamespaceDescription> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NamespaceDescription> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.pinecone.proto.NamespaceDescription getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

