// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector_service.proto

package io.pinecone.proto;

/**
 * <pre>
 * The query results for a single `QueryVector`
 * </pre>
 *
 * Protobuf type {@code SingleQueryResults}
 */
public final class SingleQueryResults extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SingleQueryResults)
    SingleQueryResultsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SingleQueryResults.newBuilder() to construct.
  private SingleQueryResults(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SingleQueryResults() {
    matches_ = java.util.Collections.emptyList();
    namespace_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SingleQueryResults();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SingleQueryResults(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              matches_ = new java.util.ArrayList<io.pinecone.proto.ScoredVector>();
              mutable_bitField0_ |= 0x00000001;
            }
            matches_.add(
                input.readMessage(io.pinecone.proto.ScoredVector.parser(), extensionRegistry));
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            namespace_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        matches_ = java.util.Collections.unmodifiableList(matches_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.pinecone.proto.VectorServiceOuterClass.internal_static_SingleQueryResults_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.pinecone.proto.VectorServiceOuterClass.internal_static_SingleQueryResults_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.pinecone.proto.SingleQueryResults.class, io.pinecone.proto.SingleQueryResults.Builder.class);
  }

  public static final int MATCHES_FIELD_NUMBER = 1;
  private java.util.List<io.pinecone.proto.ScoredVector> matches_;
  /**
   * <pre>
   * The matches for the vectors.
   * </pre>
   *
   * <code>repeated .ScoredVector matches = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.pinecone.proto.ScoredVector> getMatchesList() {
    return matches_;
  }
  /**
   * <pre>
   * The matches for the vectors.
   * </pre>
   *
   * <code>repeated .ScoredVector matches = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.pinecone.proto.ScoredVectorOrBuilder> 
      getMatchesOrBuilderList() {
    return matches_;
  }
  /**
   * <pre>
   * The matches for the vectors.
   * </pre>
   *
   * <code>repeated .ScoredVector matches = 1;</code>
   */
  @java.lang.Override
  public int getMatchesCount() {
    return matches_.size();
  }
  /**
   * <pre>
   * The matches for the vectors.
   * </pre>
   *
   * <code>repeated .ScoredVector matches = 1;</code>
   */
  @java.lang.Override
  public io.pinecone.proto.ScoredVector getMatches(int index) {
    return matches_.get(index);
  }
  /**
   * <pre>
   * The matches for the vectors.
   * </pre>
   *
   * <code>repeated .ScoredVector matches = 1;</code>
   */
  @java.lang.Override
  public io.pinecone.proto.ScoredVectorOrBuilder getMatchesOrBuilder(
      int index) {
    return matches_.get(index);
  }

  public static final int NAMESPACE_FIELD_NUMBER = 2;
  private volatile java.lang.Object namespace_;
  /**
   * <pre>
   * The namespace for the vectors.
   * </pre>
   *
   * <code>string namespace = 2;</code>
   * @return The namespace.
   */
  @java.lang.Override
  public java.lang.String getNamespace() {
    java.lang.Object ref = namespace_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      namespace_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The namespace for the vectors.
   * </pre>
   *
   * <code>string namespace = 2;</code>
   * @return The bytes for namespace.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNamespaceBytes() {
    java.lang.Object ref = namespace_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      namespace_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < matches_.size(); i++) {
      output.writeMessage(1, matches_.get(i));
    }
    if (!getNamespaceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, namespace_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < matches_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, matches_.get(i));
    }
    if (!getNamespaceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, namespace_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.pinecone.proto.SingleQueryResults)) {
      return super.equals(obj);
    }
    io.pinecone.proto.SingleQueryResults other = (io.pinecone.proto.SingleQueryResults) obj;

    if (!getMatchesList()
        .equals(other.getMatchesList())) return false;
    if (!getNamespace()
        .equals(other.getNamespace())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMatchesCount() > 0) {
      hash = (37 * hash) + MATCHES_FIELD_NUMBER;
      hash = (53 * hash) + getMatchesList().hashCode();
    }
    hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
    hash = (53 * hash) + getNamespace().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.pinecone.proto.SingleQueryResults parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pinecone.proto.SingleQueryResults parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pinecone.proto.SingleQueryResults parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pinecone.proto.SingleQueryResults parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pinecone.proto.SingleQueryResults parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pinecone.proto.SingleQueryResults parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pinecone.proto.SingleQueryResults parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.pinecone.proto.SingleQueryResults parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.pinecone.proto.SingleQueryResults parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.pinecone.proto.SingleQueryResults parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.pinecone.proto.SingleQueryResults parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.pinecone.proto.SingleQueryResults parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.pinecone.proto.SingleQueryResults prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The query results for a single `QueryVector`
   * </pre>
   *
   * Protobuf type {@code SingleQueryResults}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SingleQueryResults)
      io.pinecone.proto.SingleQueryResultsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.pinecone.proto.VectorServiceOuterClass.internal_static_SingleQueryResults_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.pinecone.proto.VectorServiceOuterClass.internal_static_SingleQueryResults_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.pinecone.proto.SingleQueryResults.class, io.pinecone.proto.SingleQueryResults.Builder.class);
    }

    // Construct using io.pinecone.proto.SingleQueryResults.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMatchesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (matchesBuilder_ == null) {
        matches_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        matchesBuilder_.clear();
      }
      namespace_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.pinecone.proto.VectorServiceOuterClass.internal_static_SingleQueryResults_descriptor;
    }

    @java.lang.Override
    public io.pinecone.proto.SingleQueryResults getDefaultInstanceForType() {
      return io.pinecone.proto.SingleQueryResults.getDefaultInstance();
    }

    @java.lang.Override
    public io.pinecone.proto.SingleQueryResults build() {
      io.pinecone.proto.SingleQueryResults result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.pinecone.proto.SingleQueryResults buildPartial() {
      io.pinecone.proto.SingleQueryResults result = new io.pinecone.proto.SingleQueryResults(this);
      int from_bitField0_ = bitField0_;
      if (matchesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          matches_ = java.util.Collections.unmodifiableList(matches_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.matches_ = matches_;
      } else {
        result.matches_ = matchesBuilder_.build();
      }
      result.namespace_ = namespace_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.pinecone.proto.SingleQueryResults) {
        return mergeFrom((io.pinecone.proto.SingleQueryResults)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.pinecone.proto.SingleQueryResults other) {
      if (other == io.pinecone.proto.SingleQueryResults.getDefaultInstance()) return this;
      if (matchesBuilder_ == null) {
        if (!other.matches_.isEmpty()) {
          if (matches_.isEmpty()) {
            matches_ = other.matches_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMatchesIsMutable();
            matches_.addAll(other.matches_);
          }
          onChanged();
        }
      } else {
        if (!other.matches_.isEmpty()) {
          if (matchesBuilder_.isEmpty()) {
            matchesBuilder_.dispose();
            matchesBuilder_ = null;
            matches_ = other.matches_;
            bitField0_ = (bitField0_ & ~0x00000001);
            matchesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMatchesFieldBuilder() : null;
          } else {
            matchesBuilder_.addAllMessages(other.matches_);
          }
        }
      }
      if (!other.getNamespace().isEmpty()) {
        namespace_ = other.namespace_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.pinecone.proto.SingleQueryResults parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.pinecone.proto.SingleQueryResults) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.pinecone.proto.ScoredVector> matches_ =
      java.util.Collections.emptyList();
    private void ensureMatchesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        matches_ = new java.util.ArrayList<io.pinecone.proto.ScoredVector>(matches_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.pinecone.proto.ScoredVector, io.pinecone.proto.ScoredVector.Builder, io.pinecone.proto.ScoredVectorOrBuilder> matchesBuilder_;

    /**
     * <pre>
     * The matches for the vectors.
     * </pre>
     *
     * <code>repeated .ScoredVector matches = 1;</code>
     */
    public java.util.List<io.pinecone.proto.ScoredVector> getMatchesList() {
      if (matchesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(matches_);
      } else {
        return matchesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The matches for the vectors.
     * </pre>
     *
     * <code>repeated .ScoredVector matches = 1;</code>
     */
    public int getMatchesCount() {
      if (matchesBuilder_ == null) {
        return matches_.size();
      } else {
        return matchesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The matches for the vectors.
     * </pre>
     *
     * <code>repeated .ScoredVector matches = 1;</code>
     */
    public io.pinecone.proto.ScoredVector getMatches(int index) {
      if (matchesBuilder_ == null) {
        return matches_.get(index);
      } else {
        return matchesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The matches for the vectors.
     * </pre>
     *
     * <code>repeated .ScoredVector matches = 1;</code>
     */
    public Builder setMatches(
        int index, io.pinecone.proto.ScoredVector value) {
      if (matchesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatchesIsMutable();
        matches_.set(index, value);
        onChanged();
      } else {
        matchesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The matches for the vectors.
     * </pre>
     *
     * <code>repeated .ScoredVector matches = 1;</code>
     */
    public Builder setMatches(
        int index, io.pinecone.proto.ScoredVector.Builder builderForValue) {
      if (matchesBuilder_ == null) {
        ensureMatchesIsMutable();
        matches_.set(index, builderForValue.build());
        onChanged();
      } else {
        matchesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The matches for the vectors.
     * </pre>
     *
     * <code>repeated .ScoredVector matches = 1;</code>
     */
    public Builder addMatches(io.pinecone.proto.ScoredVector value) {
      if (matchesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatchesIsMutable();
        matches_.add(value);
        onChanged();
      } else {
        matchesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The matches for the vectors.
     * </pre>
     *
     * <code>repeated .ScoredVector matches = 1;</code>
     */
    public Builder addMatches(
        int index, io.pinecone.proto.ScoredVector value) {
      if (matchesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatchesIsMutable();
        matches_.add(index, value);
        onChanged();
      } else {
        matchesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The matches for the vectors.
     * </pre>
     *
     * <code>repeated .ScoredVector matches = 1;</code>
     */
    public Builder addMatches(
        io.pinecone.proto.ScoredVector.Builder builderForValue) {
      if (matchesBuilder_ == null) {
        ensureMatchesIsMutable();
        matches_.add(builderForValue.build());
        onChanged();
      } else {
        matchesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The matches for the vectors.
     * </pre>
     *
     * <code>repeated .ScoredVector matches = 1;</code>
     */
    public Builder addMatches(
        int index, io.pinecone.proto.ScoredVector.Builder builderForValue) {
      if (matchesBuilder_ == null) {
        ensureMatchesIsMutable();
        matches_.add(index, builderForValue.build());
        onChanged();
      } else {
        matchesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The matches for the vectors.
     * </pre>
     *
     * <code>repeated .ScoredVector matches = 1;</code>
     */
    public Builder addAllMatches(
        java.lang.Iterable<? extends io.pinecone.proto.ScoredVector> values) {
      if (matchesBuilder_ == null) {
        ensureMatchesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, matches_);
        onChanged();
      } else {
        matchesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The matches for the vectors.
     * </pre>
     *
     * <code>repeated .ScoredVector matches = 1;</code>
     */
    public Builder clearMatches() {
      if (matchesBuilder_ == null) {
        matches_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        matchesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The matches for the vectors.
     * </pre>
     *
     * <code>repeated .ScoredVector matches = 1;</code>
     */
    public Builder removeMatches(int index) {
      if (matchesBuilder_ == null) {
        ensureMatchesIsMutable();
        matches_.remove(index);
        onChanged();
      } else {
        matchesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The matches for the vectors.
     * </pre>
     *
     * <code>repeated .ScoredVector matches = 1;</code>
     */
    public io.pinecone.proto.ScoredVector.Builder getMatchesBuilder(
        int index) {
      return getMatchesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The matches for the vectors.
     * </pre>
     *
     * <code>repeated .ScoredVector matches = 1;</code>
     */
    public io.pinecone.proto.ScoredVectorOrBuilder getMatchesOrBuilder(
        int index) {
      if (matchesBuilder_ == null) {
        return matches_.get(index);  } else {
        return matchesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The matches for the vectors.
     * </pre>
     *
     * <code>repeated .ScoredVector matches = 1;</code>
     */
    public java.util.List<? extends io.pinecone.proto.ScoredVectorOrBuilder> 
         getMatchesOrBuilderList() {
      if (matchesBuilder_ != null) {
        return matchesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(matches_);
      }
    }
    /**
     * <pre>
     * The matches for the vectors.
     * </pre>
     *
     * <code>repeated .ScoredVector matches = 1;</code>
     */
    public io.pinecone.proto.ScoredVector.Builder addMatchesBuilder() {
      return getMatchesFieldBuilder().addBuilder(
          io.pinecone.proto.ScoredVector.getDefaultInstance());
    }
    /**
     * <pre>
     * The matches for the vectors.
     * </pre>
     *
     * <code>repeated .ScoredVector matches = 1;</code>
     */
    public io.pinecone.proto.ScoredVector.Builder addMatchesBuilder(
        int index) {
      return getMatchesFieldBuilder().addBuilder(
          index, io.pinecone.proto.ScoredVector.getDefaultInstance());
    }
    /**
     * <pre>
     * The matches for the vectors.
     * </pre>
     *
     * <code>repeated .ScoredVector matches = 1;</code>
     */
    public java.util.List<io.pinecone.proto.ScoredVector.Builder> 
         getMatchesBuilderList() {
      return getMatchesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.pinecone.proto.ScoredVector, io.pinecone.proto.ScoredVector.Builder, io.pinecone.proto.ScoredVectorOrBuilder> 
        getMatchesFieldBuilder() {
      if (matchesBuilder_ == null) {
        matchesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.pinecone.proto.ScoredVector, io.pinecone.proto.ScoredVector.Builder, io.pinecone.proto.ScoredVectorOrBuilder>(
                matches_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        matches_ = null;
      }
      return matchesBuilder_;
    }

    private java.lang.Object namespace_ = "";
    /**
     * <pre>
     * The namespace for the vectors.
     * </pre>
     *
     * <code>string namespace = 2;</code>
     * @return The namespace.
     */
    public java.lang.String getNamespace() {
      java.lang.Object ref = namespace_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        namespace_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The namespace for the vectors.
     * </pre>
     *
     * <code>string namespace = 2;</code>
     * @return The bytes for namespace.
     */
    public com.google.protobuf.ByteString
        getNamespaceBytes() {
      java.lang.Object ref = namespace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        namespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The namespace for the vectors.
     * </pre>
     *
     * <code>string namespace = 2;</code>
     * @param value The namespace to set.
     * @return This builder for chaining.
     */
    public Builder setNamespace(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      namespace_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The namespace for the vectors.
     * </pre>
     *
     * <code>string namespace = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNamespace() {
      
      namespace_ = getDefaultInstance().getNamespace();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The namespace for the vectors.
     * </pre>
     *
     * <code>string namespace = 2;</code>
     * @param value The bytes for namespace to set.
     * @return This builder for chaining.
     */
    public Builder setNamespaceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      namespace_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SingleQueryResults)
  }

  // @@protoc_insertion_point(class_scope:SingleQueryResults)
  private static final io.pinecone.proto.SingleQueryResults DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.pinecone.proto.SingleQueryResults();
  }

  public static io.pinecone.proto.SingleQueryResults getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SingleQueryResults>
      PARSER = new com.google.protobuf.AbstractParser<SingleQueryResults>() {
    @java.lang.Override
    public SingleQueryResults parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SingleQueryResults(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SingleQueryResults> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SingleQueryResults> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.pinecone.proto.SingleQueryResults getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

