// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector_service.proto

// Protobuf Java Version: 3.25.2
package io.pinecone.proto;

/**
 * <pre>
 * The request for the `Update` operation.
 * </pre>
 *
 * Protobuf type {@code UpdateRequest}
 */
public final class UpdateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UpdateRequest)
    UpdateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateRequest.newBuilder() to construct.
  private UpdateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateRequest() {
    id_ = "";
    values_ = emptyFloatList();
    namespace_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return VectorServiceOuterClass.internal_static_UpdateRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return VectorServiceOuterClass.internal_static_UpdateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            UpdateRequest.class, Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object id_ = "";
  /**
   * <pre>
   * Vector's unique id.
   * </pre>
   *
   * <code>string id = 1 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The id.
   */
  @Override
  public String getId() {
    Object ref = id_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Vector's unique id.
   * </pre>
   *
   * <code>string id = 1 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for id.
   */
  @Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    Object ref = id_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.FloatList values_ =
      emptyFloatList();
  /**
   * <pre>
   * Vector data.
   * </pre>
   *
   * <code>repeated float values = 2 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return A list containing the values.
   */
  @Override
  public java.util.List<Float>
      getValuesList() {
    return values_;
  }
  /**
   * <pre>
   * Vector data.
   * </pre>
   *
   * <code>repeated float values = 2 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The count of values.
   */
  public int getValuesCount() {
    return values_.size();
  }
  /**
   * <pre>
   * Vector data.
   * </pre>
   *
   * <code>repeated float values = 2 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @param index The index of the element to return.
   * @return The values at the given index.
   */
  public float getValues(int index) {
    return values_.getFloat(index);
  }
  private int valuesMemoizedSerializedSize = -1;

  public static final int SPARSE_VALUES_FIELD_NUMBER = 5;
  private SparseValues sparseValues_;
  /**
   * <code>.SparseValues sparse_values = 5;</code>
   * @return Whether the sparseValues field is set.
   */
  @Override
  public boolean hasSparseValues() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.SparseValues sparse_values = 5;</code>
   * @return The sparseValues.
   */
  @Override
  public SparseValues getSparseValues() {
    return sparseValues_ == null ? SparseValues.getDefaultInstance() : sparseValues_;
  }
  /**
   * <code>.SparseValues sparse_values = 5;</code>
   */
  @Override
  public SparseValuesOrBuilder getSparseValuesOrBuilder() {
    return sparseValues_ == null ? SparseValues.getDefaultInstance() : sparseValues_;
  }

  public static final int SET_METADATA_FIELD_NUMBER = 3;
  private com.google.protobuf.Struct setMetadata_;
  /**
   * <pre>
   * Metadata to *set* for the vector.
   * </pre>
   *
   * <code>.google.protobuf.Struct set_metadata = 3 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the setMetadata field is set.
   */
  @Override
  public boolean hasSetMetadata() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Metadata to *set* for the vector.
   * </pre>
   *
   * <code>.google.protobuf.Struct set_metadata = 3 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The setMetadata.
   */
  @Override
  public com.google.protobuf.Struct getSetMetadata() {
    return setMetadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : setMetadata_;
  }
  /**
   * <pre>
   * Metadata to *set* for the vector.
   * </pre>
   *
   * <code>.google.protobuf.Struct set_metadata = 3 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  @Override
  public com.google.protobuf.StructOrBuilder getSetMetadataOrBuilder() {
    return setMetadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : setMetadata_;
  }

  public static final int NAMESPACE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile Object namespace_ = "";
  /**
   * <pre>
   * Namespace name where to update the vector.
   * </pre>
   *
   * <code>string namespace = 4 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The namespace.
   */
  @Override
  public String getNamespace() {
    Object ref = namespace_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      namespace_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Namespace name where to update the vector.
   * </pre>
   *
   * <code>string namespace = 4 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for namespace.
   */
  @Override
  public com.google.protobuf.ByteString
      getNamespaceBytes() {
    Object ref = namespace_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      namespace_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (getValuesList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(valuesMemoizedSerializedSize);
    }
    for (int i = 0; i < values_.size(); i++) {
      output.writeFloatNoTag(values_.getFloat(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getSetMetadata());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(namespace_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, namespace_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getSparseValues());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    {
      int dataSize = 0;
      dataSize = 4 * getValuesList().size();
      size += dataSize;
      if (!getValuesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      valuesMemoizedSerializedSize = dataSize;
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSetMetadata());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(namespace_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, namespace_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getSparseValues());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof UpdateRequest)) {
      return super.equals(obj);
    }
    UpdateRequest other = (UpdateRequest) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getValuesList()
        .equals(other.getValuesList())) return false;
    if (hasSparseValues() != other.hasSparseValues()) return false;
    if (hasSparseValues()) {
      if (!getSparseValues()
          .equals(other.getSparseValues())) return false;
    }
    if (hasSetMetadata() != other.hasSetMetadata()) return false;
    if (hasSetMetadata()) {
      if (!getSetMetadata()
          .equals(other.getSetMetadata())) return false;
    }
    if (!getNamespace()
        .equals(other.getNamespace())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (getValuesCount() > 0) {
      hash = (37 * hash) + VALUES_FIELD_NUMBER;
      hash = (53 * hash) + getValuesList().hashCode();
    }
    if (hasSparseValues()) {
      hash = (37 * hash) + SPARSE_VALUES_FIELD_NUMBER;
      hash = (53 * hash) + getSparseValues().hashCode();
    }
    if (hasSetMetadata()) {
      hash = (37 * hash) + SET_METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getSetMetadata().hashCode();
    }
    hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
    hash = (53 * hash) + getNamespace().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static UpdateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UpdateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UpdateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UpdateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UpdateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UpdateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UpdateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UpdateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static UpdateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static UpdateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static UpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(UpdateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The request for the `Update` operation.
   * </pre>
   *
   * Protobuf type {@code UpdateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UpdateRequest)
      UpdateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return VectorServiceOuterClass.internal_static_UpdateRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return VectorServiceOuterClass.internal_static_UpdateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UpdateRequest.class, Builder.class);
    }

    // Construct using io.pinecone.proto.UpdateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSparseValuesFieldBuilder();
        getSetMetadataFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      values_ = emptyFloatList();
      sparseValues_ = null;
      if (sparseValuesBuilder_ != null) {
        sparseValuesBuilder_.dispose();
        sparseValuesBuilder_ = null;
      }
      setMetadata_ = null;
      if (setMetadataBuilder_ != null) {
        setMetadataBuilder_.dispose();
        setMetadataBuilder_ = null;
      }
      namespace_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return VectorServiceOuterClass.internal_static_UpdateRequest_descriptor;
    }

    @Override
    public UpdateRequest getDefaultInstanceForType() {
      return UpdateRequest.getDefaultInstance();
    }

    @Override
    public UpdateRequest build() {
      UpdateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public UpdateRequest buildPartial() {
      UpdateRequest result = new UpdateRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(UpdateRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        values_.makeImmutable();
        result.values_ = values_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.sparseValues_ = sparseValuesBuilder_ == null
            ? sparseValues_
            : sparseValuesBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.setMetadata_ = setMetadataBuilder_ == null
            ? setMetadata_
            : setMetadataBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.namespace_ = namespace_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof UpdateRequest) {
        return mergeFrom((UpdateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(UpdateRequest other) {
      if (other == UpdateRequest.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.values_.isEmpty()) {
        if (values_.isEmpty()) {
          values_ = other.values_;
          values_.makeImmutable();
          bitField0_ |= 0x00000002;
        } else {
          ensureValuesIsMutable();
          values_.addAll(other.values_);
        }
        onChanged();
      }
      if (other.hasSparseValues()) {
        mergeSparseValues(other.getSparseValues());
      }
      if (other.hasSetMetadata()) {
        mergeSetMetadata(other.getSetMetadata());
      }
      if (!other.getNamespace().isEmpty()) {
        namespace_ = other.namespace_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 21: {
              float v = input.readFloat();
              ensureValuesIsMutable();
              values_.addFloat(v);
              break;
            } // case 21
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              int alloc = length > 4096 ? 4096 : length;
              ensureValuesIsMutable(alloc / 4);
              while (input.getBytesUntilLimit() > 0) {
                values_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getSetMetadataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 26
            case 34: {
              namespace_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getSparseValuesFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object id_ = "";
    /**
     * <pre>
     * Vector's unique id.
     * </pre>
     *
     * <code>string id = 1 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The id.
     */
    public String getId() {
      Object ref = id_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Vector's unique id.
     * </pre>
     *
     * <code>string id = 1 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Vector's unique id.
     * </pre>
     *
     * <code>string id = 1 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Vector's unique id.
     * </pre>
     *
     * <code>string id = 1 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Vector's unique id.
     * </pre>
     *
     * <code>string id = 1 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.FloatList values_ = emptyFloatList();
    private void ensureValuesIsMutable() {
      if (!values_.isModifiable()) {
        values_ = makeMutableCopy(values_);
      }
      bitField0_ |= 0x00000002;
    }
    private void ensureValuesIsMutable(int capacity) {
      if (!values_.isModifiable()) {
        values_ = makeMutableCopy(values_, capacity);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <pre>
     * Vector data.
     * </pre>
     *
     * <code>repeated float values = 2 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return A list containing the values.
     */
    public java.util.List<Float>
        getValuesList() {
      values_.makeImmutable();
      return values_;
    }
    /**
     * <pre>
     * Vector data.
     * </pre>
     *
     * <code>repeated float values = 2 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The count of values.
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <pre>
     * Vector data.
     * </pre>
     *
     * <code>repeated float values = 2 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param index The index of the element to return.
     * @return The values at the given index.
     */
    public float getValues(int index) {
      return values_.getFloat(index);
    }
    /**
     * <pre>
     * Vector data.
     * </pre>
     *
     * <code>repeated float values = 2 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param index The index to set the value at.
     * @param value The values to set.
     * @return This builder for chaining.
     */
    public Builder setValues(
        int index, float value) {

      ensureValuesIsMutable();
      values_.setFloat(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Vector data.
     * </pre>
     *
     * <code>repeated float values = 2 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The values to add.
     * @return This builder for chaining.
     */
    public Builder addValues(float value) {

      ensureValuesIsMutable();
      values_.addFloat(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Vector data.
     * </pre>
     *
     * <code>repeated float values = 2 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param values The values to add.
     * @return This builder for chaining.
     */
    public Builder addAllValues(
        Iterable<? extends Float> values) {
      ensureValuesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, values_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Vector data.
     * </pre>
     *
     * <code>repeated float values = 2 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearValues() {
      values_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private SparseValues sparseValues_;
    private com.google.protobuf.SingleFieldBuilderV3<
        SparseValues, SparseValues.Builder, SparseValuesOrBuilder> sparseValuesBuilder_;
    /**
     * <code>.SparseValues sparse_values = 5;</code>
     * @return Whether the sparseValues field is set.
     */
    public boolean hasSparseValues() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.SparseValues sparse_values = 5;</code>
     * @return The sparseValues.
     */
    public SparseValues getSparseValues() {
      if (sparseValuesBuilder_ == null) {
        return sparseValues_ == null ? SparseValues.getDefaultInstance() : sparseValues_;
      } else {
        return sparseValuesBuilder_.getMessage();
      }
    }
    /**
     * <code>.SparseValues sparse_values = 5;</code>
     */
    public Builder setSparseValues(SparseValues value) {
      if (sparseValuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sparseValues_ = value;
      } else {
        sparseValuesBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.SparseValues sparse_values = 5;</code>
     */
    public Builder setSparseValues(
        SparseValues.Builder builderForValue) {
      if (sparseValuesBuilder_ == null) {
        sparseValues_ = builderForValue.build();
      } else {
        sparseValuesBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.SparseValues sparse_values = 5;</code>
     */
    public Builder mergeSparseValues(SparseValues value) {
      if (sparseValuesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          sparseValues_ != null &&
          sparseValues_ != SparseValues.getDefaultInstance()) {
          getSparseValuesBuilder().mergeFrom(value);
        } else {
          sparseValues_ = value;
        }
      } else {
        sparseValuesBuilder_.mergeFrom(value);
      }
      if (sparseValues_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.SparseValues sparse_values = 5;</code>
     */
    public Builder clearSparseValues() {
      bitField0_ = (bitField0_ & ~0x00000004);
      sparseValues_ = null;
      if (sparseValuesBuilder_ != null) {
        sparseValuesBuilder_.dispose();
        sparseValuesBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.SparseValues sparse_values = 5;</code>
     */
    public SparseValues.Builder getSparseValuesBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getSparseValuesFieldBuilder().getBuilder();
    }
    /**
     * <code>.SparseValues sparse_values = 5;</code>
     */
    public SparseValuesOrBuilder getSparseValuesOrBuilder() {
      if (sparseValuesBuilder_ != null) {
        return sparseValuesBuilder_.getMessageOrBuilder();
      } else {
        return sparseValues_ == null ?
            SparseValues.getDefaultInstance() : sparseValues_;
      }
    }
    /**
     * <code>.SparseValues sparse_values = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        SparseValues, SparseValues.Builder, SparseValuesOrBuilder>
        getSparseValuesFieldBuilder() {
      if (sparseValuesBuilder_ == null) {
        sparseValuesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            SparseValues, SparseValues.Builder, SparseValuesOrBuilder>(
                getSparseValues(),
                getParentForChildren(),
                isClean());
        sparseValues_ = null;
      }
      return sparseValuesBuilder_;
    }

    private com.google.protobuf.Struct setMetadata_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> setMetadataBuilder_;
    /**
     * <pre>
     * Metadata to *set* for the vector.
     * </pre>
     *
     * <code>.google.protobuf.Struct set_metadata = 3 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the setMetadata field is set.
     */
    public boolean hasSetMetadata() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Metadata to *set* for the vector.
     * </pre>
     *
     * <code>.google.protobuf.Struct set_metadata = 3 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The setMetadata.
     */
    public com.google.protobuf.Struct getSetMetadata() {
      if (setMetadataBuilder_ == null) {
        return setMetadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : setMetadata_;
      } else {
        return setMetadataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Metadata to *set* for the vector.
     * </pre>
     *
     * <code>.google.protobuf.Struct set_metadata = 3 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder setSetMetadata(com.google.protobuf.Struct value) {
      if (setMetadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        setMetadata_ = value;
      } else {
        setMetadataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Metadata to *set* for the vector.
     * </pre>
     *
     * <code>.google.protobuf.Struct set_metadata = 3 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder setSetMetadata(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (setMetadataBuilder_ == null) {
        setMetadata_ = builderForValue.build();
      } else {
        setMetadataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Metadata to *set* for the vector.
     * </pre>
     *
     * <code>.google.protobuf.Struct set_metadata = 3 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder mergeSetMetadata(com.google.protobuf.Struct value) {
      if (setMetadataBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          setMetadata_ != null &&
          setMetadata_ != com.google.protobuf.Struct.getDefaultInstance()) {
          getSetMetadataBuilder().mergeFrom(value);
        } else {
          setMetadata_ = value;
        }
      } else {
        setMetadataBuilder_.mergeFrom(value);
      }
      if (setMetadata_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Metadata to *set* for the vector.
     * </pre>
     *
     * <code>.google.protobuf.Struct set_metadata = 3 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder clearSetMetadata() {
      bitField0_ = (bitField0_ & ~0x00000008);
      setMetadata_ = null;
      if (setMetadataBuilder_ != null) {
        setMetadataBuilder_.dispose();
        setMetadataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Metadata to *set* for the vector.
     * </pre>
     *
     * <code>.google.protobuf.Struct set_metadata = 3 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public com.google.protobuf.Struct.Builder getSetMetadataBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getSetMetadataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Metadata to *set* for the vector.
     * </pre>
     *
     * <code>.google.protobuf.Struct set_metadata = 3 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public com.google.protobuf.StructOrBuilder getSetMetadataOrBuilder() {
      if (setMetadataBuilder_ != null) {
        return setMetadataBuilder_.getMessageOrBuilder();
      } else {
        return setMetadata_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : setMetadata_;
      }
    }
    /**
     * <pre>
     * Metadata to *set* for the vector.
     * </pre>
     *
     * <code>.google.protobuf.Struct set_metadata = 3 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getSetMetadataFieldBuilder() {
      if (setMetadataBuilder_ == null) {
        setMetadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getSetMetadata(),
                getParentForChildren(),
                isClean());
        setMetadata_ = null;
      }
      return setMetadataBuilder_;
    }

    private Object namespace_ = "";
    /**
     * <pre>
     * Namespace name where to update the vector.
     * </pre>
     *
     * <code>string namespace = 4 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The namespace.
     */
    public String getNamespace() {
      Object ref = namespace_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        namespace_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Namespace name where to update the vector.
     * </pre>
     *
     * <code>string namespace = 4 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The bytes for namespace.
     */
    public com.google.protobuf.ByteString
        getNamespaceBytes() {
      Object ref = namespace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        namespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Namespace name where to update the vector.
     * </pre>
     *
     * <code>string namespace = 4 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The namespace to set.
     * @return This builder for chaining.
     */
    public Builder setNamespace(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      namespace_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Namespace name where to update the vector.
     * </pre>
     *
     * <code>string namespace = 4 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearNamespace() {
      namespace_ = getDefaultInstance().getNamespace();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Namespace name where to update the vector.
     * </pre>
     *
     * <code>string namespace = 4 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The bytes for namespace to set.
     * @return This builder for chaining.
     */
    public Builder setNamespaceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      namespace_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UpdateRequest)
  }

  // @@protoc_insertion_point(class_scope:UpdateRequest)
  private static final UpdateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new UpdateRequest();
  }

  public static UpdateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateRequest>() {
    @Override
    public UpdateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<UpdateRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public UpdateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

