// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db_data_2025-10.proto
// Protobuf Java Version: 4.29.3

package io.pinecone.proto;

public interface UpsertResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpsertResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The number of vectors upserted.
   * </pre>
   *
   * <code>uint32 upserted_count = 1 [json_name = "upsertedCount"];</code>
   * @return The upsertedCount.
   */
  int getUpsertedCount();
}
