// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector_service.proto

// Protobuf Java Version: 3.25.2
package io.pinecone.proto;

public final class VectorServiceOuterClass {
  private VectorServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SparseValues_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SparseValues_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Vector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Vector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ScoredVector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ScoredVector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestUnion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestUnion_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpsertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpsertRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpsertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpsertResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FetchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FetchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FetchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FetchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FetchResponse_VectorsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FetchResponse_VectorsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pagination_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Pagination_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryVector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QueryVector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SingleQueryResults_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SingleQueryResults_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QueryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Usage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Usage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DescribeIndexStatsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DescribeIndexStatsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NamespaceSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NamespaceSummary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DescribeIndexStatsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DescribeIndexStatsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DescribeIndexStatsResponse_NamespacesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DescribeIndexStatsResponse_NamespacesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024vector_service.proto\032\034google/protobuf/" +
      "struct.proto\032\034google/api/annotations.pro" +
      "to\032\037google/api/field_behavior.proto\032.pro" +
      "toc-gen-openapiv2/options/annotations.pr" +
      "oto\"\200\001\n\014SparseValues\0226\n\007indices\030\001 \003(\rB%\222" +
      "A\036J\026[1, 312, 822, 14, 980]x\350\007\200\001\001\342A\001\002\0228\n\006" +
      "values\030\002 \003(\002B(\222A!J\031[0.1, 0.2, 0.3, 0.4, " +
      "0.5]x\350\007\200\001\001\342A\001\002\"\377\001\n\006Vector\022-\n\002id\030\001 \001(\tB!\222" +
      "A\032J\022\"example-vector-1\"x\200\004\200\001\001\342A\001\002\022H\n\006valu" +
      "es\030\002 \003(\002B8\222A1J([0.1, 0.2, 0.3, 0.4, 0.5," +
      " 0.6, 0.7, 0.8]x\240\234\001\200\001\001\342A\001\002\022$\n\rsparse_val" +
      "ues\030\004 \001(\0132\r.SparseValues\022V\n\010metadata\030\003 \001" +
      "(\0132\027.google.protobuf.StructB+\222A(J&{\"genr" +
      "e\": \"documentary\", \"year\": 2019}\"\224\002\n\014Sco" +
      "redVector\022-\n\002id\030\001 \001(\tB!\222A\032J\022\"example-vec" +
      "tor-1\"x\200\004\200\001\001\342A\001\002\022\030\n\005score\030\002 \001(\002B\t\222A\006J\0040." +
      "08\022=\n\006values\030\003 \003(\002B-\222A*J([0.1, 0.2, 0.3," +
      " 0.4, 0.5, 0.6, 0.7, 0.8]\022$\n\rsparse_valu" +
      "es\030\005 \001(\0132\r.SparseValues\022V\n\010metadata\030\004 \001(" +
      "\0132\027.google.protobuf.StructB+\222A(J&{\"genre" +
      "\": \"documentary\", \"year\": 2019}\"\211\001\n\014Requ" +
      "estUnion\022 \n\006upsert\030\001 \001(\0132\016.UpsertRequest" +
      "H\000\022 \n\006delete\030\002 \001(\0132\016.DeleteRequestH\000\022 \n\006" +
      "update\030\003 \001(\0132\016.UpdateRequestH\000B\023\n\021Reques" +
      "tUnionInner\"e\n\rUpsertRequest\022\'\n\007vectors\030" +
      "\001 \003(\0132\007.VectorB\r\222A\006x\350\007\200\001\001\342A\001\002\022+\n\tnamespa" +
      "ce\030\002 \001(\tB\030\222A\025J\023\"example-namespace\"\"1\n\016Up" +
      "sertResponse\022\037\n\016upserted_count\030\001 \001(\rB\007\222A" +
      "\004J\00210\"\266\001\n\rDeleteRequest\022(\n\003ids\030\001 \003(\tB\033\222A" +
      "\030J\020[\"id-0\", \"id-1\"]x\350\007\200\001\001\022%\n\ndelete_all\030" +
      "\002 \001(\010B\021\222A\016:\005falseJ\005false\022+\n\tnamespace\030\003 " +
      "\001(\tB\030\222A\025J\023\"example-namespace\"\022\'\n\006filter\030" +
      "\004 \001(\0132\027.google.protobuf.Struct\"\020\n\016Delete" +
      "Response\"i\n\014FetchRequest\022,\n\003ids\030\001 \003(\tB\037\222" +
      "A\030J\020[\"id-0\", \"id-1\"]x\350\007\200\001\001\342A\001\002\022+\n\tnamesp" +
      "ace\030\002 \001(\tB\030\222A\025J\023\"example-namespace\"\"\341\001\n\r" +
      "FetchResponse\022,\n\007vectors\030\001 \003(\0132\033.FetchRe" +
      "sponse.VectorsEntry\022+\n\tnamespace\030\002 \001(\tB\030" +
      "\222A\025J\023\"example-namespace\"\0222\n\005usage\030\003 \001(\0132" +
      "\006.UsageB\026\222A\023J\021{\"read_units\": 5}H\000\210\001\001\0327\n\014" +
      "VectorsEntry\022\013\n\003key\030\001 \001(\t\022\026\n\005value\030\002 \001(\013" +
      "2\007.Vector:\0028\001B\010\n\006_usage\"\370\001\n\013ListRequest\022" +
      ",\n\006prefix\030\001 \001(\tB\027\222A\024J\014\"document1#\"x\350\007\200\001\001" +
      "H\000\210\001\001\022 \n\005limit\030\002 \001(\rB\014\222A\t:\003100J\00212H\001\210\001\001\022" +
      "B\n\020pagination_token\030\003 \001(\tB#\222A J\036\"Tm90aGl" +
      "uZyB0byBzZWUgaGVyZQo=\"H\002\210\001\001\022+\n\tnamespace" +
      "\030\004 \001(\tB\030\222A\025J\023\"example-namespace\"B\t\n\007_pre" +
      "fixB\010\n\006_limitB\023\n\021_pagination_token\"?\n\nPa" +
      "gination\0221\n\004next\030\001 \001(\tB#\222A J\036\"Tm90aGluZy" +
      "B0byBzZWUgaGVyZQo=\"\",\n\010ListItem\022 \n\002id\030\001 " +
      "\001(\tB\024\222A\021J\017\"document1#abb\"\"\203\002\n\014ListRespon" +
      "se\022S\n\007vectors\030\001 \003(\0132\t.ListItemB7\222A4J2[{\"" +
      "id\": \"document1#abb\"}, {\"id\": \"document1" +
      "#abc\"}]\022$\n\npagination\030\002 \001(\0132\013.Pagination" +
      "H\000\210\001\001\022+\n\tnamespace\030\003 \001(\tB\030\222A\025J\023\"example-" +
      "namespace\"\0222\n\005usage\030\004 \001(\0132\006.UsageB\026\222A\023J\021" +
      "{\"read_units\": 1}H\001\210\001\001B\r\n\013_paginationB\010\n" +
      "\006_usage\"\321\002\n\013QueryVector\022H\n\006values\030\001 \003(\002B" +
      "8\222A1J([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7" +
      ", 0.8]x\240\234\001\200\001\001\342A\001\002\022$\n\rsparse_values\030\005 \001(\013" +
      "2\r.SparseValues\022(\n\005top_k\030\002 \001(\rB\031\222A\026J\00210Y" +
      "\000\000\000\000\000\210\303@i\000\000\000\000\000\000\360?\022+\n\tnamespace\030\003 \001(\tB\030\222A" +
      "\025J\023\"example-namespace\"\022{\n\006filter\030\004 \001(\0132\027" +
      ".google.protobuf.StructBR\222AOJM{\"genre\": " +
      "{\"$in\": [\"comedy\", \"documentary\", \"drama" +
      "\"]}, \"year\": {\"$eq\": 2019}}\"\373\003\n\014QueryReq" +
      "uest\022+\n\tnamespace\030\001 \001(\tB\030\222A\025J\023\"example-n" +
      "amespace\"\022,\n\005top_k\030\002 \001(\rB\035\222A\026J\00210Y\000\000\000\000\000\210" +
      "\303@i\000\000\000\000\000\000\360?\342A\001\002\022{\n\006filter\030\003 \001(\0132\027.google" +
      ".protobuf.StructBR\222AOJM{\"genre\": {\"$in\":" +
      " [\"comedy\", \"documentary\", \"drama\"]}, \"y" +
      "ear\": {\"$eq\": 2019}}\022(\n\016include_values\030\004" +
      " \001(\010B\020\222A\r:\005falseJ\004true\022*\n\020include_metada" +
      "ta\030\005 \001(\010B\020\222A\r:\005falseJ\004true\022)\n\007queries\030\006 " +
      "\003(\0132\014.QueryVectorB\n\030\001\222A\005x\n\200\001\001\022D\n\006vector\030" +
      "\007 \003(\002B4\222A1J([0.1, 0.2, 0.3, 0.4, 0.5, 0." +
      "6, 0.7, 0.8]x\240\234\001\200\001\001\022$\n\rsparse_vector\030\t \001" +
      "(\0132\r.SparseValues\022&\n\002id\030\010 \001(\tB\032\222A\027J\022\"exa" +
      "mple-vector-1\"x\200\004\"a\n\022SingleQueryResults\022" +
      "\036\n\007matches\030\001 \003(\0132\r.ScoredVector\022+\n\tnames" +
      "pace\030\002 \001(\tB\030\222A\025J\023\"example-namespace\"\"\252\001\n" +
      "\rQueryResponse\022(\n\007results\030\001 \003(\0132\023.Single" +
      "QueryResultsB\002\030\001\022\036\n\007matches\030\002 \003(\0132\r.Scor" +
      "edVector\022\021\n\tnamespace\030\003 \001(\t\0222\n\005usage\030\004 \001" +
      "(\0132\006.UsageB\026\222A\023J\021{\"read_units\": 5}H\000\210\001\001B" +
      "\010\n\006_usage\"7\n\005Usage\022\037\n\nread_units\030\001 \001(\rB\006" +
      "\222A\003J\0015H\000\210\001\001B\r\n\013_read_units\"\263\002\n\rUpdateReq" +
      "uest\022-\n\002id\030\001 \001(\tB!\222A\032J\022\"example-vector-1" +
      "\"x\200\004\200\001\001\342A\001\002\022D\n\006values\030\002 \003(\002B4\222A1J([0.1, " +
      "0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]x\240\234\001\200\001" +
      "\001\022$\n\rsparse_values\030\005 \001(\0132\r.SparseValues\022" +
      "Z\n\014set_metadata\030\003 \001(\0132\027.google.protobuf." +
      "StructB+\222A(J&{\"genre\": \"documentary\", \"y" +
      "ear\": 2019}\022+\n\tnamespace\030\004 \001(\tB\030\222A\025J\023\"ex" +
      "ample-namespace\"\"\020\n\016UpdateResponse\"D\n\031De" +
      "scribeIndexStatsRequest\022\'\n\006filter\030\001 \001(\0132" +
      "\027.google.protobuf.Struct\"4\n\020NamespaceSum" +
      "mary\022 \n\014vector_count\030\001 \001(\rB\n\222A\007J\00550000\"\232" +
      "\003\n\032DescribeIndexStatsResponse\022?\n\nnamespa" +
      "ces\030\001 \003(\0132+.DescribeIndexStatsResponse.N" +
      "amespacesEntry\022\034\n\tdimension\030\002 \001(\rB\t\222A\006J\004" +
      "1024\022 \n\016index_fullness\030\003 \001(\002B\010\222A\005J\0030.4\022&" +
      "\n\022total_vector_count\030\004 \001(\rB\n\222A\007J\00580000\032D" +
      "\n\017NamespacesEntry\022\013\n\003key\030\001 \001(\t\022 \n\005value\030" +
      "\002 \001(\0132\021.NamespaceSummary:\0028\001:\214\001\222A\210\0012\205\001{\"" +
      "namespaces\": {\"\": {\"vectorCount\": 50000}" +
      ", \"example-namespace-2\": {\"vectorCount\":" +
      " 30000}}, \"dimension\": 1024, \"index_full" +
      "ness\": 0.4}2\225\006\n\rVectorService\022c\n\006Upsert\022" +
      "\016.UpsertRequest\032\017.UpsertResponse\"8\222A\033\n\021V" +
      "ector Operations*\006upsert\202\323\344\223\002\024\"\017/vectors" +
      "/upsert:\001*\022v\n\006Delete\022\016.DeleteRequest\032\017.D" +
      "eleteResponse\"K\222A\033\n\021Vector Operations*\006d" +
      "elete\202\323\344\223\002\'\"\017/vectors/delete:\001*Z\021*\017/vect" +
      "ors/delete\022[\n\005Fetch\022\r.FetchRequest\032\016.Fet" +
      "chResponse\"3\222A\032\n\021Vector Operations*\005fetc" +
      "h\202\323\344\223\002\020\022\016/vectors/fetch\022V\n\004List\022\014.ListRe" +
      "quest\032\r.ListResponse\"1\222A\031\n\021Vector Operat" +
      "ions*\004list\202\323\344\223\002\017\022\r/vectors/list\022V\n\005Query" +
      "\022\r.QueryRequest\032\016.QueryResponse\".\222A\032\n\021Ve" +
      "ctor Operations*\005query\202\323\344\223\002\013\"\006/query:\001*\022" +
      "c\n\006Update\022\016.UpdateRequest\032\017.UpdateRespon" +
      "se\"8\222A\033\n\021Vector Operations*\006update\202\323\344\223\002\024" +
      "\"\017/vectors/update:\001*\022\264\001\n\022DescribeIndexSt" +
      "ats\022\032.DescribeIndexStatsRequest\032\033.Descri" +
      "beIndexStatsResponse\"e\222A)\n\021Vector Operat" +
      "ions*\024describe_index_stats\202\323\344\223\0023\"\025/descr" +
      "ibe_index_stats:\001*Z\027\022\025/describe_index_st" +
      "atsB\274\003\n\021io.pinecone.protoP\001Z+github.com/" +
      "pinecone-io/go-pinecone/pinecone\222A\366\002\022K\n\014" +
      "Pinecone API\";\n\017Pinecone.io Ops\022\023https:/" +
      "/pinecone.io\032\023support@pinecone.io\0329{inde" +
      "x_name}-{project_name}.svc.{environment}" +
      ".pinecone.io*\001\0022\020application/json:\020appli" +
      "cation/jsonZx\nv\n\nApiKeyAuth\022h\010\002\022YAn API " +
      "Key is required to call Pinecone APIs. G" +
      "et yours at https://www.pinecone.io/star" +
      "t/\032\007Api-Key \002b\020\n\016\n\nApiKeyAuth\022\000r9\n\031More " +
      "Pinecone.io API docs\022\034https://www.pineco" +
      "ne.io/docsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          grpc.gateway.protoc_gen_openapiv2.options.Annotations.getDescriptor(),
        });
    internal_static_SparseValues_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SparseValues_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SparseValues_descriptor,
        new String[] { "Indices", "Values", });
    internal_static_Vector_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Vector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Vector_descriptor,
        new String[] { "Id", "Values", "SparseValues", "Metadata", });
    internal_static_ScoredVector_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ScoredVector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ScoredVector_descriptor,
        new String[] { "Id", "Score", "Values", "SparseValues", "Metadata", });
    internal_static_RequestUnion_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RequestUnion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestUnion_descriptor,
        new String[] { "Upsert", "Delete", "Update", "RequestUnionInner", });
    internal_static_UpsertRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_UpsertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpsertRequest_descriptor,
        new String[] { "Vectors", "Namespace", });
    internal_static_UpsertResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_UpsertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpsertResponse_descriptor,
        new String[] { "UpsertedCount", });
    internal_static_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteRequest_descriptor,
        new String[] { "Ids", "DeleteAll", "Namespace", "Filter", });
    internal_static_DeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_DeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteResponse_descriptor,
        new String[] { });
    internal_static_FetchRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_FetchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FetchRequest_descriptor,
        new String[] { "Ids", "Namespace", });
    internal_static_FetchResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_FetchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FetchResponse_descriptor,
        new String[] { "Vectors", "Namespace", "Usage", });
    internal_static_FetchResponse_VectorsEntry_descriptor =
      internal_static_FetchResponse_descriptor.getNestedTypes().get(0);
    internal_static_FetchResponse_VectorsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FetchResponse_VectorsEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_ListRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_ListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListRequest_descriptor,
        new String[] { "Prefix", "Limit", "PaginationToken", "Namespace", });
    internal_static_Pagination_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_Pagination_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Pagination_descriptor,
        new String[] { "Next", });
    internal_static_ListItem_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_ListItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListItem_descriptor,
        new String[] { "Id", });
    internal_static_ListResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_ListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListResponse_descriptor,
        new String[] { "Vectors", "Pagination", "Namespace", "Usage", });
    internal_static_QueryVector_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_QueryVector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QueryVector_descriptor,
        new String[] { "Values", "SparseValues", "TopK", "Namespace", "Filter", });
    internal_static_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QueryRequest_descriptor,
        new String[] { "Namespace", "TopK", "Filter", "IncludeValues", "IncludeMetadata", "Queries", "Vector", "SparseVector", "Id", });
    internal_static_SingleQueryResults_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_SingleQueryResults_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SingleQueryResults_descriptor,
        new String[] { "Matches", "Namespace", });
    internal_static_QueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_QueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QueryResponse_descriptor,
        new String[] { "Results", "Matches", "Namespace", "Usage", });
    internal_static_Usage_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_Usage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Usage_descriptor,
        new String[] { "ReadUnits", });
    internal_static_UpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_UpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateRequest_descriptor,
        new String[] { "Id", "Values", "SparseValues", "SetMetadata", "Namespace", });
    internal_static_UpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_UpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateResponse_descriptor,
        new String[] { });
    internal_static_DescribeIndexStatsRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_DescribeIndexStatsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DescribeIndexStatsRequest_descriptor,
        new String[] { "Filter", });
    internal_static_NamespaceSummary_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_NamespaceSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NamespaceSummary_descriptor,
        new String[] { "VectorCount", });
    internal_static_DescribeIndexStatsResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_DescribeIndexStatsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DescribeIndexStatsResponse_descriptor,
        new String[] { "Namespaces", "Dimension", "IndexFullness", "TotalVectorCount", });
    internal_static_DescribeIndexStatsResponse_NamespacesEntry_descriptor =
      internal_static_DescribeIndexStatsResponse_descriptor.getNestedTypes().get(0);
    internal_static_DescribeIndexStatsResponse_NamespacesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DescribeIndexStatsResponse_NamespacesEntry_descriptor,
        new String[] { "Key", "Value", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(grpc.gateway.protoc_gen_openapiv2.options.Annotations.openapiv2Field);
    registry.add(grpc.gateway.protoc_gen_openapiv2.options.Annotations.openapiv2Operation);
    registry.add(grpc.gateway.protoc_gen_openapiv2.options.Annotations.openapiv2Schema);
    registry.add(grpc.gateway.protoc_gen_openapiv2.options.Annotations.openapiv2Swagger);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.StructProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    grpc.gateway.protoc_gen_openapiv2.options.Annotations.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
