/*
 * Pinecone Control Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-10
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.db_control.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.db_control.client.model.ReadCapacityDedicatedConfig;
import org.openapitools.db_control.client.model.ReadCapacityStatus;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.db_control.client.JSON;

/**
 * ReadCapacityDedicatedSpecResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-23T14:25:31.700489Z[Etc/UTC]")
public class ReadCapacityDedicatedSpecResponse {
  public static final String SERIALIZED_NAME_MODE = "mode";
  @SerializedName(SERIALIZED_NAME_MODE)
  private String mode;

  public static final String SERIALIZED_NAME_DEDICATED = "dedicated";
  @SerializedName(SERIALIZED_NAME_DEDICATED)
  private ReadCapacityDedicatedConfig dedicated;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private ReadCapacityStatus status;

  public ReadCapacityDedicatedSpecResponse() {
  }

  public ReadCapacityDedicatedSpecResponse mode(String mode) {
    
    this.mode = mode;
    return this;
  }

   /**
   * The mode of the index. Possible values: &#x60;OnDemand&#x60; or &#x60;Dedicated&#x60;. Defaults to &#x60;OnDemand&#x60;. If set to &#x60;Dedicated&#x60;, &#x60;dedicated.node_type&#x60;, and &#x60;dedicated.scaling&#x60; must be specified.
   * @return mode
  **/
  @javax.annotation.Nonnull
  public String getMode() {
    return mode;
  }


  public void setMode(String mode) {
    this.mode = mode;
  }


  public ReadCapacityDedicatedSpecResponse dedicated(ReadCapacityDedicatedConfig dedicated) {
    
    this.dedicated = dedicated;
    return this;
  }

   /**
   * Get dedicated
   * @return dedicated
  **/
  @javax.annotation.Nonnull
  public ReadCapacityDedicatedConfig getDedicated() {
    return dedicated;
  }


  public void setDedicated(ReadCapacityDedicatedConfig dedicated) {
    this.dedicated = dedicated;
  }


  public ReadCapacityDedicatedSpecResponse status(ReadCapacityStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nonnull
  public ReadCapacityStatus getStatus() {
    return status;
  }


  public void setStatus(ReadCapacityStatus status) {
    this.status = status;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReadCapacityDedicatedSpecResponse readCapacityDedicatedSpecResponse = (ReadCapacityDedicatedSpecResponse) o;
    return Objects.equals(this.mode, readCapacityDedicatedSpecResponse.mode) &&
        Objects.equals(this.dedicated, readCapacityDedicatedSpecResponse.dedicated) &&
        Objects.equals(this.status, readCapacityDedicatedSpecResponse.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mode, dedicated, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReadCapacityDedicatedSpecResponse {\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    dedicated: ").append(toIndentedString(dedicated)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("mode");
    openapiFields.add("dedicated");
    openapiFields.add("status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("mode");
    openapiRequiredFields.add("dedicated");
    openapiRequiredFields.add("status");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ReadCapacityDedicatedSpecResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ReadCapacityDedicatedSpecResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReadCapacityDedicatedSpecResponse is not found in the empty JSON string", ReadCapacityDedicatedSpecResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ReadCapacityDedicatedSpecResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ReadCapacityDedicatedSpecResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ReadCapacityDedicatedSpecResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("mode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `mode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mode").toString()));
      }
      // validate the required field `dedicated`
      ReadCapacityDedicatedConfig.validateJsonElement(jsonObj.get("dedicated"));
      // validate the required field `status`
      ReadCapacityStatus.validateJsonElement(jsonObj.get("status"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReadCapacityDedicatedSpecResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReadCapacityDedicatedSpecResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReadCapacityDedicatedSpecResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReadCapacityDedicatedSpecResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ReadCapacityDedicatedSpecResponse>() {
           @Override
           public void write(JsonWriter out, ReadCapacityDedicatedSpecResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ReadCapacityDedicatedSpecResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ReadCapacityDedicatedSpecResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ReadCapacityDedicatedSpecResponse
  * @throws IOException if the JSON string is invalid with respect to ReadCapacityDedicatedSpecResponse
  */
  public static ReadCapacityDedicatedSpecResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReadCapacityDedicatedSpecResponse.class);
  }

 /**
  * Convert an instance of ReadCapacityDedicatedSpecResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

